### ISSUE TITLE
Support for GitHub CLI?

### ISSUE THREAD

**Issue by Jarmos-san** [zsh-users/zsh-completions#1005]
It appears support for [GitHub CLI](https://cli.github.com) is missing from the repository. Adding it shouldn't be a difficult task & I'm willing to share a PR to add it here.

**Comment by syohex** [comment]
Github CLI supports shell completions itself. So we don't support it by our policy. You can use its zsh completion by the following commands.

```
gh completion --shell zsh > /some_fpath_directory/_gh
```

**Comment by ww7** [comment]
and `rm -f ~/.zcompdump; compinit`
