### ISSUE TITLE
How are these completions generated?

### ISSUE THREAD

**Issue by bartekpacia** [zsh-users/zsh-completions#1061]
Hi, thanks to everyone contributing and maintaining this project.

I'm wondering how all these completions were generated? Surely no one types them by hand. Is there some tool that is usually used for generating completions out of commands `--help`?

**Comment by syohex** [comment]
Unfortunately most completion files are written by hand. Some completion files generates completion code. There are no specifications of `--help` output and a lot of commands use their own `--help` output, so it is difficult to parse them in common way.

BTW in these days, we could generate zsh completion files by using ChatGPT or AI systems.
