### ISSUE TITLE
Flutter completion not working

### ISSUE THREAD

**Issue by bartekpacia** [zsh-users/zsh-completions#1062]
Since I mainly work with Flutter these days, I'm happy to see that this repo contains completions for both `dart` and `flutter`. However I'm unable to get the latter one to work on my machine – i.e. it uses the default behavior of listing files in my $PWD instead of printing commands and options of `flutter` tool. I'll gladly accept any help and explanation! 

### Debugging

I tried using tips from [this SO answer](https://unix.stackexchange.com/a/606305/417321).

Running `dart <(Ctrl+X ?)>` prints:

whereas `flutter <(Ctrl+X ?)>` prints:

<img width="682" alt="Screenshot 2023-12-07 at 4 59 12 PM" src="https://github.com/zsh-users/zsh-completions/assets/40357511/0e6e2309-8ec0-436e-8cc9-c252890d028a">

So something's definitely off.

<img width="682" alt="scr1" src="https://github.com/zsh-users/zsh-completions/assets/40357511/73b76d96-9afb-4183-b3c3-07ccb8a936f9">

### Environment

```
$ uname -a
Darwin Barteks-MacBook.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103 arm64
```

```
$ zsh --version
zsh 5.9 (arm-apple-darwin21.3.0)
```

```
$ echo $FPATH | tr ':' '\n'
/Users/bartek/.oh-my-zsh/plugins/swiftpm
/Users/bartek/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
/Users/bartek/.oh-my-zsh/custom/plugins/zsh-autosuggestions
/Users/bartek/.oh-my-zsh/plugins/pod
/Users/bartek/.oh-my-zsh/plugins/macos
/Users/bartek/.oh-my-zsh/plugins/gradle
/Users/bartek/.oh-my-zsh/plugins/fzf
/Users/bartek/.oh-my-zsh/plugins/brew
/Users/bartek/.oh-my-zsh/plugins/adb
/Users/bartek/.oh-my-zsh/plugins/1password
/Users/bartek/.oh-my-zsh/functions
/Users/bartek/.oh-my-zsh/completions
/Users/bartek/.oh-my-zsh/cache/completions
/Users/bartek/.oh-my-zsh/custom/plugins/zsh-completions/src
/opt/homebrew/share/zsh/site-functions
/usr/local/share/zsh/site-functions
/usr/share/zsh/site-functions
/usr/share/zsh/5.9/functions
/opt/homebrew/share/zsh/site-functions
```

```
$ ls -1 ~/.oh-my-zsh/custom/plugins/zsh-completions/src | grep -E 'dart|flutter'
_dart
_flutter
```

**Comment by syohex** [comment]
I can't reproduce your issue. Do other completions work on your platform ?

![a](https://github.com/zsh-users/zsh-completions/assets/554281/3d525eb5-96a9-4a28-94fe-7ae3982fc0e6)

**Comment by bartekpacia** [comment]
Now I tried and neither `dart` nor `flutter` completions work. `go` also doesn't work, but _some_ other completions work, for example `swiftpm` and `gradle`.

<details><summary>zshrc</summary>

```shell
plugins=(
	1password
	adb
	brew
	# docker - works automatically when brew-installed
	# dotnet
	`#fzf` $([ -x "$(command -v fzf)" ] && echo 'fzf')
	flutter
	gradle
	macos
	pod
	zsh-autosuggestions
	zsh-syntax-highlighting
	swiftpm
)

if command -v brew >/dev/null 2>&1; then
	# Set up completions for `brew` command and `brew`-installed programs
	# See: https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh
	FPATH="$(brew --prefix)/share/zsh/site-functions:$FPATH"
fi

if [ -d "$ZSH" ]; then
	source "$ZSH/oh-my-zsh.sh"
	# oh-my-zsh initializes completion, so shrc needs to be sourced before it.
	# oh-my-zsh sets aliases, so aliases needs to be sourced after it.
fi
```

</details> 

What could be the cause? I know I'm likely asking for a lot, but any tips are appreciated!
