### ISSUE TITLE
Mix completion for `phx.gen.live`

### ISSUE THREAD

**Issue by simonzsolt** [zsh-users/zsh-completions#1067]
I wanted to make a small contribution to add this completion: https://hexdocs.pm/phoenix/Mix.Tasks.Phx.Gen.Live.html for `mix`. I have a branch ready. Can you please grant access to push to a new branch, so I can open a PR?

**Comment by syohex** [comment]
You can send pull request without the permission of this repo. Please fork this repo under your account or organization, push some commits and send pull request.

- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
