### ISSUE TITLE
Completions for fvm are broken as of fvm v3

### ISSUE THREAD

**Issue by bartekpacia** [zsh-users/zsh-completions#1075]
Completion script in question: https://github.com/zsh-users/zsh-completions/blob/master/src/_fvm

As of latest `fvm` v3.0.0, the above completion script doesn't work. Learn more in https://github.com/leoafarias/fvm/issues/689

ping @syohex who created it (huge thank you and kudos!)

**Comment by syohex** [comment]
Thanks for reporting issue. It seems fvm supports zsh completion itself now. I'll remove fvm completion from this repository according to our policy.

**Comment by bartekpacia** [comment]
> It seems fvm supports zsh completion itself now. 

Hmm, does it? What do you mean?

**Comment by syohex** [comment]
I tried new `fvm`. It generates completion files(e.g. `~/.dart-cli-completion/fvm.zsh`) under `~/.dart-cli-completion/` and it appends its configuration in the zsh configuration file(`.zshrc` etc)

**Comment by bartekpacia** [comment]
>  It generates completion files(e.g. ~/.dart-cli-completion/fvm.zsh) under ~/.dart-cli-completion/ and it appends its configuration in the zsh configuration file(.zshrc etc)

Ah right, it uses [this package](https://pub.dev/packages/cli_completion). But it doesn't work on my machine for some reason. Thanks for checking!

> it appends its configuration in the zsh configuration file(.zshrc etc)

I really don't like this behavior. I want my completion scripts to live in e.g. `/opt/homebrew/share/zsh/site-functions/`, and not modify (!) my dotfiles and `~/.config`.

**Comment by bartekpacia** [comment]
So yeah, let's remove `_fvm` from this repo.

Did you write that completion script manually?

**Comment by syohex** [comment]
> Did you write that completion script manually?

Yes

**Comment by syohex** [comment]
I've removed it at #1076
