### ISSUE TITLE
Request: add PDM 

### ISSUE THREAD

**Issue by jahagirdar** [zsh-users/zsh-completions#1090]
https://pdm-project.org/latest/#__tabbed_5_2

```
# Make sure ~/.zfunc is added to fpath, before compinit.
pdm completion zsh > ~/.zfunc/_pdm
```

**Comment by syohex** [comment]
I'm afraid that we cannot add the completion that is supported by its own project/repository according to our policy. Please see [CONTRIBUTING.md](https://github.com/zsh-users/zsh-completions/blob/master/CONTRIBUTING.md)
