### ISSUE TITLE
zsh: do you whish to see all possibilities

### ISSUE THREAD

**Issue by AlexBurdu** [zsh-users/zsh-completions#1099]
with zsh-completion plugin set up every time I type `l` (for ls) or `c` (for cd) I am interrupted by the error in the title: `zsh: do you whish to see all possibilities`.

I have to handle the prompt before I am able to type the command I need. 

This only happens if I have a small terminal window (which I usually keep)

<img width="548" alt="image" src="https://github.com/user-attachments/assets/b6c814b1-2f45-429b-acc8-20b642b4c990">

**Comment by syohex** [comment]
I think it is [zsh-autocomplete](https://github.com/marlonrichert/zsh-autocomplete) feature not zsh-completion's. Please ask them  your issue.

Related issue
- https://github.com/marlonrichert/zsh-autocomplete/issues/329
