### ISSUE TITLE
Added homebrew-cask support to _brew. Need help moving forward...

### ISSUE THREAD

**Issue by mbgearhead** [zsh-users/zsh-completions#182]
Like many others mac users, I use homebrew as my package manager and have recently found extension project homebrew-cask (https://github.com/phinze/homebrew-cask) which allows you to install native osx software (gui stuff) within the confines of homebrew. For example, to install firefox, you would type "brew cask install firefox". I'm very new to writing completions files, but I think I have successfully added cask tab-completion to the homebrew zsh-completion file _brew (See here: https://gist.github.com/mbgearhead/7187772). This works, but it is rough. What would be the best way to concisely check for the existence of homebrew-cask so that these completions only show up when a user has installed cask? Anyway, any input you could give me would be greatly appreciated. Thanks,

- Miles

**Comment by nicoulaj** [comment]
homebrew completion is now maintained directly in homebrew project.
