### ISSUE TITLE
About license

### ISSUE THREAD

**Issue by arcan1s** [zsh-users/zsh-completions#207]
I have looked at files and found that 50 of 98 files do not have any license. But other 48 files have BSD license and all of them belong to <b>zsh-users</b> (but I could be wrong).
So, I want to suggest:
* To license all of 50 files under BSD.
* To license new files under BSD too and maybe to ask contributors for transfer of copyright to <b>zsh-users</b>. Or maybe to license under BSD new files only.

Why is it needed? We will have a package under one license. And we will not have items with "unknown" license.

[Licenses of 0.11.0 version](https://gist.github.com/arcan1s/8404308)

**Comment by rrooij** [comment]
This is still an important issue in my opinion, since it can't be included in FSF-endorsed distributions because of the missing licenses.

**Comment by rrooij** [comment]
@glidenote 
Can you please add license information to:
* _ag
* _gist
* _httpie
* _rubocop
* _wemux

@sorin-ionescu 
Can you please add license information to:
* _atach
* _gas
* _srm
* _taskwarrior

* _zarg

**Comment by sorin-ionescu** [comment]
@rrooij 
- \_atach: MIT
- \_gas: MIT
- \_srm: MIT
- \_taskwarrior: MIT (missing)
- \_zargs: MIT-like (missing)

**Comment by mmckinst** [comment]
I was just looking at packaging this for Fedora but ran in to this issue.

It looks like some of these are lifted from other sources, assuming there's a copyright there, we can just copy it to the file. For example _brew came from https://github.com/Homebrew/homebrew/blob/master/Library/Contributions/brew_zsh_completion.zsh which has a [BSD license](https://github.com/Homebrew/homebrew/blob/master/LICENSE.txt)

**Comment by mmckinst** [comment]
Down to 52 without a license. https://gist.github.com/mmckinst/3b9049d285c75d3a3572

**Comment by nicoulaj** [comment]
@mmckinst thanks for your work !

To everyone cc'ed, can you please take a look at [mmckinst's table](https://gist.github.com/mmckinst/3b9049d285c75d3a3572) and submit pull requests to add license headers ?

@hhatto @lencioni @dongweiming	@vasilykraev @Valodim @vhbit @shtouff @alexvollmer @tpope @dadrc @benohara @markupboy @technolize @jozefizso @mitukiii @pismute @nono @mafrosis @aki77 @mbrgm

We will wait a bit so that people add license headers to their compdefs, and I guess at some point we will just remove the remaining ones.

**Comment by nicoulaj** [comment]
Thanks to everyone who sent a pull request.

We still have 38 compdefs without a license:

| compdef  | contributor / source |
| ------------- | ------------- |
| `_atach`  | @sorin-ionescu  |
| `_celery` | @dongwm |
| `_cmake` | @kastiglione|
| `_cpanm` | @rshhh |
| `_dget` | @KrisShannon |
| `_ditz`  | @technolize |
| `_docker-machine`  | @ilkka |
| `_drush`  | @vasilykraev |
| `_dzen2`  | @Valodim |
| `_fab` | @vhbit |
| `_gas`  | Fredrik Wallgren <fredrik.wallgren@gmail.com> |
| `_gem`  | @alexvollmer @tpope |
| `_google` | @dadrc / @benohara |
| `_heroku` | Ali B. (http://awhitebox.com) |
| `_hledger`  | @Valodim |
| `_id3` / `_id3v2` | @Valodim|
| `_iw` | @vapniks |
| `_jekyll` | @blindFS |
| `_lein`  | @technolize |
| `_logger`  | @Valodim |
| `_lunar` | @Valodim |
| `_lunchy`  | @markupboy |
| `_manage.py`   | @technolize |
| `_pactree`  | @luolimao |
| `_pear`  | @aki77 |
| `_pgsql_utils`  | http://www.zsh.org/mla/users/2004/msg01006.html |
| `_port`  | @g5pw |
| `_primus`  | @luolimao  |
| `_ralio`  | @peteryates |
| `_rebar` | https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/rebar/_rebar |
| `_socat`  | @Valodim |
| `_srm ` | @sorin-ionescu |
| `_symfony` | @aki77 |
| `_tarsnap`  | Daniel Teunis |
| `_tmuxinator`  | @Soliah |
| `_veewee`  | @mbrgm |
| `_yaourt`  | ? |

To everyone notified, can you please add a license header to the compdef you contributed and send a pull request ? You can find an example [here](https://github.com/zsh-users/zsh-completions/blob/master/src/_ack).

**Comment by kastiglione** [comment]
@nicoulaj I didn't contribute the original `_cmake` compdef, only a small pull request.

**Comment by nicoulaj** [comment]
@kastiglione sorry, fixed.

**Comment by tpope** [comment]
Same, for `_gem`.

**Comment by g5pw** [comment]
Mailed the the other co-authors of `_port`, waiting for a response before commiting header.

**Comment by dadrc** [comment]
I'm not sure how my code landed in zsh-users, must have been @benohara. But I'm fine with both a BSD license and a copyright transfer to zsh-users.

**Comment by nicoulaj** [comment]
Thank you.

Here is an updated table of missing licenses:

| compdef  | contributor / source |
| ------------- | ------------- |
| `_atach`  | @sorin-ionescu  |
| `_celery` | @dongwm |
| `_cmake` | @pablospe|
| `_cpanm` | @rshhh |
| `_dget` | @KrisShannon |
| `_ditz`  | @technolize |
| `_dzen2`  | @Valodim |
| `_gas`  | @walle |
| `_gem`  | @alexvollmer |
| `_hledger`  | @Valodim |
| `_id3` / `_id3v2` | @Valodim|
| `_iw` | @vapniks |
| `_jekyll` | @blindFS |
| `_lein`  | @technolize |
| `_logger`  | @Valodim |
| `_lunar` | @Valodim |
| `_lunchy`  | @markupboy |
| `_manage.py`   | @technolize |
| `_pactree`  | @luolimao |
| `_pear`  | @aki77 |
| `_primus`  | @luolimao  |
| `_rebar`  | @goofansu  |
| `_socat`  | @Valodim |
| `_srm ` | @sorin-ionescu |
| `_tarsnap` | daniel@teunis.cc > mail sent |
| `_symfony` | @aki77 |
| `_veewee`  | @mbrgm |

**Comment by nicoulaj** [comment]
To everyone mentionned in the table, this is the last chance.

In a few days, I will delete the files that have no license header and release a version.

| compdef  | contributor / source |
| ------------- | ------------- |
| `_celery` | @dongwm |
| `_cpanm` | @rshhh |
| `_dget` | @KrisShannon |
| `_ditz`  | @technolize |
| `_dzen2`  | @Valodim |
| `_gem`  | @alexvollmer |
| `_hledger`  | @Valodim |
| `_id3` / `_id3v2` | @Valodim|
| `_iw` | @vapniks |
| `_jekyll` | @blindFS |
| `_lein`  | @technolize |
| `_logger`  | @Valodim |
| `_lunar` | @Valodim |
| `_manage.py`   | @technolize |
| `_pactree`  | @luolimao |
| `_pear`  | @aki77 |
| `_primus`  | @luolimao  |
| `_rebar`  | @goofansu  |
| `_socat`  | @Valodim |
| `_tarsnap` | daniel@teunis.cc > mail sent |
| `_symfony` | @aki77 |
| `_veewee`  | @mbrgm |

**Comment by syohex** [comment]
`_dget` PR is https://github.com/zsh-users/zsh-completions/pull/449

**Comment by nicoulaj** [comment]
I removed the remaining compdefs and released version 0.20.0.
