### ISSUE TITLE
virtualbox

### ISSUE THREAD

**Issue by euri10** [zsh-users/zsh-completions#238]
when I type vboxmanage <TAB> i got 2 options
vboxmanage VBoxManage

hitting tab after vboxmanage completes with _virtualbox
hitting tab after VBoxManage completes with all the options contained in _virtualbox

I'd like both option to operate like the VBoxManage one, what am I doing wrong please ?

**Comment by nicoulaj** [comment]
Same here, it works correctly. Try with an empty zshrc.
