### ISSUE TITLE
pip3 completion

### ISSUE THREAD

**Issue by netheril96** [zsh-users/zsh-completions#266]
In a lot of system, the `pip` command for python version 3+ is renamed (or symlinked to) `pip3`, and this no longer benefits from zsh auto completion. Is there any chance that the completion for `pip3` can be implemented? I guess that it will not be very hard, since it is the same as `pip`, just a different name for invocation.

**Comment by blueyed** [comment]
@netheril96 
It works in my adoption: https://gist.github.com/blueyed/54a257c411310a28805a - you might want to try it.
