### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by nono** [zsh-users/zsh-completions#276]
Hello,

there was a zsh completion script for golang in the official repository but it was removed. The 1.4 version was released yesterday, without the script. It could be a good idea to host it in zsh-completions, and improve it by the way.

https://github.com/golang/go/commit/ddbefae97ef0dd506da22eab811574d57a4f2a3b

**Comment by dufferzafar** [comment]
:+1:

**Comment by nicoulaj** [comment]
See #355

**Comment by ninrod** [comment]
not working for go 1.9
