### ISSUE TITLE
_arguments error in _ag script

### ISSUE THREAD

**Issue by scanny** [zsh-users/zsh-completions#286]
I'm on OS X 10.9.2 running zsh version 5.0.2, the built-in version I believe.

I'm getting this error when attempting completions on ag (the silver searcher):

```zsh
$ ag <TAB>
_arguments:comparguments:312: invalid option definition: --ackmate[-A --after [LINES]      Print lines before match (Default: 2)]
```
I've narrowed it down to this offending line:
https://github.com/zsh-users/zsh-completions/blob/master/src/_ag#L78
If this line is removed, everything works fine, except the file-type matching options don't appear. This change was introduced in the latest commit involving this file. Apparently there is just the original addition and the one change:
https://github.com/zsh-users/zsh-completions/commits/master/src/_ag

Interestingly, this line is identical to this one in the _ack script (excepting the variable name), and the _ack script works as intended:
https://github.com/zsh-users/zsh-completions/blob/master/src/_ack#L140

The trouble seems at least obliquely related to issue #135.

My shell scripting skills aren't quite up to understanding how it's forming the _ag_types variable.

I also can't quite decode why the ` {'--','--no'}${_ag_types/ ##/\[}']'` match string does what it does, although it seems cool to be able to pop in a bunch of dynamic options using some sort of array expansion or something.

If someone can help me debug it I'm happy to prepare a PR. If it's easier just to fix it, I'd love to know what made it (not) tick :)

**Comment by leandrocp** [comment]
Same happens here. How can I help ?

**Comment by scanny** [comment]
@leandrocp I ended up just removing line 78 and it works fine for me now. That line was added in the latest commit for this completion script, apparently to add a listing of '--py' and other file-type options to the completion choices. It was pretty close to a copy/paste from the ack completion but apparently not fully tested. I don't miss having the file-type options available. There are so many it scrolls off my screen and I only ever use a few so I've never had occasion to need a reminder in the middle of a command.

**Comment by starcraftman** [comment]
@scanny @leandrocp  Hi, this is a late reply but is this still an issue? Nobody pinged me via @ so I didn't know there was an issue. I can't reproduce. Looking back, I am a bit dissapointed in my solution, might try to make it easier to read.

If it still persists, try these two lines one at a time in your zsh shell.
`_ag_types=( ${(f)"$(ag --list-file-types | awk ' /--/ { VAR=$1; gsub(/--/, "", VAR); getline; gsub(/^ */, ""); printf "%s %s\n", VAR, $0 } ')"} )`

`echo '--'${_ag_types/ ##/\[}']'`

**Comment by starcraftman** [comment]
Ok I think I know what the problem was, --list-file-types was added with 0.22. I'm bisecting the versions to make the completer more robust. I imagine that you guys have since upgraded at least once so if you are >= 0.22 you should be good.

I'm gonna make a new PR that will fix this anyhow, since ag unstable makes sense to be able to add options per version.

**Comment by starcraftman** [comment]
@hhatto This can be closed, I'm almost 100% positive it was a result of not version checking before invoking `ag --list-file-types`. No problem on new one, everything past version 20 is checked against version.
