### ISSUE TITLE
Completion for adb conflicts with zsh's version

### ISSUE THREAD

**Issue by blueyed** [zsh-users/zsh-completions#291]
Zsh ships completion for `adb` already:
https://sourceforge.net/p/zsh/code/ci/master/tree/Completion/Unix/Command/_adb

Here's the one from zsh-users/zsh-completions: https://github.com/zsh-users/zsh-completions/blob/master/src/_adb

I've not investigated which version is better, and if features from this repo's version could / should be included in zsh's distribution.

**Comment by nicoulaj** [comment]
Thanks, removed from here.

**Comment by blueyed** [comment]
@nicoulaj 
Thanks a lot for the latest work / merges!
