### ISSUE TITLE
providing zsh completion generator

### ISSUE THREAD

**Issue by xh3b4sd** [zsh-users/zsh-completions#294]
What about providing a simple generator for zsh completions? I just found https://github.com/RobSis/zsh-completion-generator. 

This looks poorly documented. I don't know how to generate a completion with multiple levels of subcommands. Further it looks complicated and the source file feels like a mess. 

I am asking here because I am not a zsh-completion-superhero as maybe you folks. I think many people would love have a simple script that just creates a zsh completion based on a easy to write config file like json or yaml. 

Opinions on that?

**Comment by nicoulaj** [comment]
This is not the goal of this project, I suggest you discuss this on zsh mailing lists.
