### ISSUE TITLE
Poor performance in tab-completion, can't track down

### ISSUE THREAD

**Issue by quicknir** [zsh-users/zsh-completions#314]
Hello,

I've been having issues with tab completion being slow under very specific circumstances. Basically, if I go into a prompt and type a random name and try to tab complete, I get an incredibly long pause (like 10 seconds). This also happens if I type cd and then a random string of characters. What's interesting is that this will happen once, and then if I try it again it doesn't happen. But hours or a day later, it happens again. 

This suggested to me some kind of caching behavior. But right after I do this, I check .zcompdump, and the modified date has not been updated. 

As background, there's an NFS directory mounted that don't have the best performance, and my PATH contains quite a few subdirectories from this NFS.

I've made quite a few changes to combat these issues in my init.zsh inside the completion module.

unsetopt PATH_DIRS           # Perform path search even on command names with slashes.

zstyle ':completion:*:*files' ignored-patterns '/NFS_DIR*'
zstyle ':completion:*:*directories' ignored-patterns '/NFS_DIR*'
zstyle ':completion:*:*commands' ignored-patterns '/NFS_DIR*'
zstyle ':completion:*:functions' ignored-patterns '(_*|pre(cmd|exec)):/NFS_DIR*'

zstyle ':completion:*:*:cd:*' tag-order local-directories directory-stack #path-directories
zstyle ':completion:*:-tilde-:*' group-order 'named-directories' #'path-directories' 'users' 'expand'

zstyle ':completion:*:approximate:*' max-errors 0 numeric
#zstyle -e ':completion:*:approximate:*' max-errors 'reply=($((($#PREFIX+$#SUFFIX)/3))numeric)'

It would seem to me that I've pretty thoroughly eliminated the NFS directories and various forms of approximate completion that might slow it down. Yet the problem persists. Anyone have any ideas? Doing code bisection is a pain because I can only trigger the behavior every several hours.

**Comment by nicoulaj** [comment]
You should ask this question on zsh mailing-lists.

**Comment by quicknir** [comment]
I totally lost track of this, fwiw I eventually resolved this issue. It ended up being that getting the completion list of users was taking forever, and the list of users is actually used for a lot of completions. For instance, even when you do cd, you can follow it with a username to go directly to that user's home directory.

It might be worth noting somewhere as this setup at organization where user home dirs are NFS mounted is fairly common, and I wouldn't be surprised if it's also very common that getting a fill list of users takes a long time.

**Comment by nicoulaj** [comment]
Oh, It might be a NIS issue in this case. If you are using NIS, you should make sure nscd is started and works correctly.

**Comment by quicknir** [comment]
Pardon my ignorance, I'm not familiar with what NIS is. If it has to do
with the properties of how NFS is setup, it may not be easily practical in
some cases (like mine) to request this be adjusted by sys admins for a
relatively minor thing like this. I think it's at least useful for people
to know about the potentially expensive USERS lookup, because there's a
non-trivial set of people for which it has very low utility and very high
cost; basically anyone working at a company with a similar NFS setup,
because you can never be logged in as anyone else or access their home
directories. I'm slightly embarrassed to admit it but it probably took me
months of spending a few minutes here and there to eventually fix this
issue. Each time a very slow lookup occurred, the list of USERS would get
cached, so it could only be easily repro'ed every few hours. So I basically
found this via binary searching with an iteration time of a day, which took
a while :-). Might save someone trouble in the future to have a sort mini
"Help, I'm having long pauses FAQ" where some of the potentially expensive
auto completions are discussed (or maybe there already is one and this can
be added).

**Comment by benskyio** [comment]
Hi guys, for me, this 30k file caused my slowness:

~/.oh-my-zsh/cache/Mac_applications.sh

I moved it out of that directory and now zsh autocomplete is screaming again. 

Hope this helps someone.

bensky
