### ISSUE TITLE
Please add completion for choosing version to be installed in apt

### ISSUE THREAD

**Issue by Temp24354** [zsh-users/zsh-completions#315]
According to http://qref.sourceforge.net/Debian/quick-reference/ch-package.en.html, users can do apt-get install package=version in order to install a concrete version of the package. Could you please add a completion for it? Thank you.

**Comment by starcraftman** [comment]
@Temp24354 Late reply, but that completion isn't tracked here. It is part of the main zsh project. You'll have to report this request to their mailing list I believe (see [here](http://sourceforge.net/p/zsh/bugs/)). This completions project only tracks new/unmerged completions. I really wish zsh used a proper bug tracker, not a fan of ML method.

You can see apt-get completion is at the zsh mirror https://github.com/zsh-users/zsh/blob/master/Completion/Debian/Command/_apt .
