### ISSUE TITLE
invalid option -c for stat on Mac OS X/FreeBSD

### ISSUE THREAD

**Issue by eirnym** [zsh-users/zsh-completions#322]
`stat -c` valid only with GNU stat(1), please add support for Mac OS X/FreeBSD systems

``` shell
$ port uninstall <TAB>stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
```

**Comment by eirnym** [comment]
Following code can be used instead:

``` zsh
  reg_time=$(stat -t '%Z' $check_file)
  comp_time=$(stat -t '%Z' $1)
  [[ $reg_time < $comp_time ]];
  return $?
```

**Comment by benohara** [comment]
I ran into this in the _vagrant completion, but using gnu stat.

The current code, only works if i remove 116, guess it should check for version of stat?

  115     case $(uname -s) in
! 116         Darwin) STATCMD="stat -f '%c'" ;;
  117         *)      STATCMD="stat -c '%Z'" ;;
  118     esac

**Comment by okapia** [comment]
Isn't it perhaps possible to do:
```
  [[ $check_file -ot $1 ]]
```

**Comment by syohex** [comment]
NOTE: `port` and `vagrand` completion no longer use `stat -c` on macOS

**Comment by syohex** [comment]
`port` completion works on macOS and any BSD and `vagrant `completion works on linux and macOS(vagrant does not support any BSD).  I suppose we can close this issue now

**Comment by eirnym** [comment]
> `port` completion works on macOS and any BSD and `vagrant `completion works on linux and macOS(vagrant does not support any BSD). I suppose we can close this issue now

It's not true, as there's at least a port for FreeBSD which is registered back in 2014: 
https://www.freshports.org/sysutils/vagrant
