### ISSUE TITLE
Add completion for dnf

### ISSUE THREAD

**Issue by saschalalala** [zsh-users/zsh-completions#326]
dnf is the new package manager in Fedora 22, but there is no completion file yet. It basically supports the same commands, yum does, so I created a copy of _yum and replaced all occurences of "yum" with "dnf" and it works flawlessly. Have a look at https://gist.github.com/saschalalala/af379b4972dd1215ce0d
Perhaps, this is going to be obsolete in a few weeks but imho, it is a nice to have ;)

**Comment by mhitza** [comment]
As of July 30, or with zsh 5.0.8-x; dnf completion is built in:

```sh
~ λ. ls -lah /usr/share/zsh/5.0.8/functions/_dnf
-rw-r--r-- 1 root root 8.1K Jul 30 19:11 /usr/share/zsh/5.0.8/functions/_dnf
                                                                                                                                                                 
~ λ. sudo dnf provides /usr/share/zsh/5.0.8/functions/_dnf 
Last metadata expiration check performed 11:09:24 ago on Sun Oct  4 03:28:17 2015.
zsh-5.0.8-5.fc22.x86_64 : Powerful interactive shell
Repo        : @System

zsh-5.0.8-5.fc22.x86_64 : Powerful interactive shell
Repo        : updates
```
