### ISSUE TITLE
Gradle completion bug on new version

### ISSUE THREAD

**Issue by Bhullnatik** [zsh-users/zsh-completions#333]
With the [new version of Gradle (2.5)](https://docs.gradle.org/current/userguide/gradle_command_line.html), the option `--no-color` was deprecated in favor of `--console=plain`, printing a warning message, this message getting caught in the completion:

<img width="682" alt="screen shot 2015-08-22 at 3 48 55 pm" src="https://cloud.githubusercontent.com/assets/2040807/9424234/5c5af548-48e5-11e5-9d48-a4a7b0940da6.png">

To fix it without breaking it for previous versions, we would need to pull the gradle version and use the correct option depending on the version.

**Comment by nicoulaj** [comment]
`_gradle` is directly in zsh now.
