### ISSUE TITLE
homebrew complete formula-specific flags?

### ISSUE THREAD

**Issue by aw1621107** [zsh-users/zsh-completions#335]
Is it possible to add autocompletion for homebrew formula-specific flags (e.g. the `zsh` formula has a `--disable-etcdir` flag, and `opam` has `--without-aspcud`, `--without-camlp4`, and `--HEAD`)? I seem to remember it being possible in bash, but I don't remember what plugins I used to achieve it; in addition, I believe git completion provides a similar option, albeit for subcommands instead of something like formulas.

**Comment by nicoulaj** [comment]
homebrew completion is now maintained in homebrew project.
