### ISSUE TITLE
adb bug of -s option for network android device

### ISSUE THREAD

**Issue by rxwen** [zsh-users/zsh-completions#338]
Say we have following connected android devices:
```
List of devices attached
192.168.0.230:5555      device
307f7bf1        device
```

When we tried to complete "-s" option, the port part of "192.168.0.230:5555" is not included in the serial number.

```
# adb -s
192.168.0.230  -- 5555:connected device
307f7bf1       -- connected device
```

The desired result should be:

```
# adb -s
192.168.0.230:5555  -- connected device
307f7bf1       -- connected device
```

**Comment by msva** [comment]
try to open _adb completion and edit line `256`.
There is `serial_numbers=(${${(M)${(f)"$(_call_program devices $service devices)"}` substring.
Try to set it to `serial_numbers=(${${(M)${(f)"$(_call_program devices $service devices)"/:/\\:}`
