### ISSUE TITLE
Color codes behind host names when using ssh completion.

### ISSUE THREAD

**Issue by RyuX51** [zsh-users/zsh-completions#342]
When using ssh completion, I always get the color codes for entries in my /.ssh/config and my /etc/hosts. (-- domain -- and -ip address -- are fine).
I'm using OS X and have this issue with Terminal and iTerm.

$ ssh (tab)
...
 -- host --
broadcasthost$'\033'\[39\;49\;00m       localhost$'\033'\[39\;49\;00m           ovh$'\033'\[39\;49\;00m                 wiki$'\033'\[39\;49\;00m
hyperion                                nas$'\033'\[39\;49\;00m                 productwiki
hyperion$'\033'\[39\;49\;00m            nas_local$'\033'\[39\;49\;00m           productwiki$'\033'\[39\;49\;00m

**Comment by nicoulaj** [comment]
ssh completion is provided by zsh, please ask this question on zsh's mailing list.
