### ISSUE TITLE
PostgreSQL client completion

### ISSUE THREAD

**Issue by nicoulaj** [zsh-users/zsh-completions#35]
Add completion for [PostgreSQL](http://www.postgresql.org/) client.

**Comment by mattdipasquale** [comment]
This doesn't seem to be working for me.

For example, the following commands don't tab complete:

* `$ postgres --versi[TAB]`
* `$ psql postg[TAB]`

Terminal just beeps at me.

Am I missing something?

I'm running zsh 5.2 (x86_64-apple-darwin15.0.0).
