### ISSUE TITLE
Release 0.10.0 is still "latest release"

### ISSUE THREAD

**Issue by apjanke** [zsh-users/zsh-completions#352]
In the GitHub releases, 0.10.0 is still marked as the "latest release"; 0.11.0 and 0.12.0 are hidden under a "..." expansion. Should 0.12.0 be marked as the latest release now?

<img width="849" alt="screen shot 2015-10-02 at 1 48 38 am" src="https://cloud.githubusercontent.com/assets/2618447/10240283/cb3ed7b8-68a7-11e5-8f7b-931334434fe4.png">

<img width="810" alt="screen shot 2015-10-02 at 1 44 11 am" src="https://cloud.githubusercontent.com/assets/2618447/10240285/d183d808-68a7-11e5-8b3d-d062fe36c568.png">

**Comment by nicoulaj** [comment]
Fixed
