### ISSUE TITLE
psql does not complete service definitions

### ISSUE THREAD

**Issue by zacchiro** [zsh-users/zsh-completions#353]
It would be nice if postgres psql completion were aware of service definitions, so that hitting "psql service=<TAB>" would help the user showing a list of available services.

Available services can be found in both `~/.pg_service.conf` and `$(pg_config --sysconfdir)/pg_service.conf` (e.g., `/etc/postgresql-common/pg_service.conf` on debian-like distros)

See http://www.postgresql.org/docs/9.4/static/libpq-pgservice.html for more info

Thanks for zsh-completions!

**Comment by nicoulaj** [comment]
Done in PR #361
