### ISSUE TITLE
Play! framework completion conflicts with SoX "play" command

### ISSUE THREAD

**Issue by simon-v** [zsh-users/zsh-completions#364]
The _play script should probably check whether or not the Play! framework is even installed or if it is the one being called.

What is the correct way to disable an unwanted completion script?

**Comment by nicoulaj** [comment]
Please ask these questions on zsh mailing lists, this project is not affiliated with the zsh project.

**Comment by simon-v** [comment]
This doesn't actually change the fact that the _play completion script, which comes with the zsh-completions package, conflicts with, and overrides, the completions for another command, also called "play", and does so regardless of whether or not the Play! framework is installed.
