### ISSUE TITLE
zsh-ycm hybrid.. could it be?

### ISSUE THREAD

**Issue by iago-lito** [zsh-users/zsh-completions#369]
[YouCompleteMe](https://github.com/Valloric/YouCompleteMe) is an awesome and snappy completion plugin for Vim, whose sophisticated fuzzy search algorithm always pulls on top of the stack the word you were looking for in a few keystrokes.

I have no idea how much this ranking algorithm is dependent on Vim environment, but 1) I guess it could be quite independent and 2) my hands are now trying to use it all the time even if not available in zsh.

I think this is enough for a feature request: how difficult would it be to take ideas from YCM ranking algorithm into zsh autocompletion engine?

killer features to me:
- matches substrings: ma**tch**th**at**name with **tchat**
- matches collapsed words: **c**amel**C**ase with **cc**, **p**ython_**s**tyle with **ps**, *etc.*
- somehow involves context

[cross-reference](https://github.com/Valloric/YouCompleteMe/issues/1908)

**Comment by nicoulaj** [comment]
I suggest you discuss this on zsh mailing lists, this is not the goal of this project.
