### ISSUE TITLE
Why does zsh completion work for VBoxManage but not vboxmanage

### ISSUE THREAD

**Issue by scinart** [zsh-users/zsh-completions#391]
[Stackoverflow](http://stackoverflow.com/questions/23130839/why-does-zsh-completion-work-for-vboxmanage-but-not-vboxmanage) doesn't give me a clear answer.

Can anyone explain to me why ``_vboxmanage()`` is defined but ``vboxmanege`` cannot be completed.

And why ``VBoxManage`` completes correctly.

**Comment by msva** [comment]
it is not a bug, but just as planned: take a look on 1st line of `_virtualbox` compdef:
```
#compdef VBoxManage=vboxmanage VBoxHeadless=vboxheadless
```
It defines which commands should be completed by which functions.

**Comment by scinart** [comment]
The [Zsh Manual](http://zsh.sourceforge.net/Doc/Release/Completion-System.html) says:
    
>    #compdef name ... [ -{p|P} pattern ... [ -N name ... ] ]

> Each name may also be of the form ``cmd=service``. When completing the command cmd, the function typically behaves as if the command service was being completed instead. 

So ``VBoxManage`` is completed as if ``vboxmanage`` is being completed, which is ``_vboxmanage()``. This works fine.

However when ``vboxmanage`` is being completed, ``_vboxmanage()`` is **not** invoked at all.

**Comment by johnLate** [comment]
I had the same issue. I think I fixed it by deleting `.zcompdump` and running `compinit`.
