### ISSUE TITLE
request: completion for borg backup

### ISSUE THREAD

**Issue by jolanouille** [zsh-users/zsh-completions#402]
I recently discovered borg, a deduplicating archiver forked from attic, and noticed that zsh does not have completions yet.

Learn more about borg on github: https://github.com/borgbackup/borg and https://borgbackup.github.io/

**Comment by blueyed** [comment]
See https://github.com/mrkmg/borgbackup-zsh-completion (linked in https://github.com/borgbackup/community/blob/master/README.rst).
(via https://github.com/borgbackup/borg/issues/1328 / https://github.com/borgbackup/community/pull/3)

**Comment by syohex** [comment]
@blueyed Thanks for information. @jolanouille Please use it.
