### ISSUE TITLE
Request: completion for Cloud Foundry CLI commands

### ISSUE THREAD

**Issue by billimek** [zsh-users/zsh-completions#412]
This completion already exists here: https://github.com/frodenas/cf-zsh-autocomplete-plugin and can be manually added - and maybe this is the way it should be handled.  I'm not clear if this falls into the category for contributing.

If so, please close this request.

If not, please consider adding or somehow referencing frodenas's cf completion as part of this repo.

**Comment by nicoulaj** [comment]
If @fredonas wants to add his compdef in this projet, I'll be happy to give him committer access. Otherwise it will stay as it is.

**Comment by frodenas** [comment]
The ownership of the `cf-zsh-autocomplete-plugin` has been transferred to @Dannyzen. I'll let him decide.

**Comment by Dannyzen** [comment]
Thanks @frodenas. @nicoulaj i'd be happy to add the compdef to this project.

**Comment by nicoulaj** [comment]
Thanks, I gave you committer access.

**Comment by Dannyzen** [comment]
thanks @nicoulaj. push direct to master okay?

**Comment by nicoulaj** [comment]
Yes (if you don't feel confident or want review you can submit a PR)

**Comment by Dannyzen** [comment]
@nicoulaj thanks. cloudfoundry completions have been [added](https://github.com/zsh-users/zsh-completions/commit/f0438a05edf669232daac65d3c26e23564c7d620)
