### ISSUE TITLE
Cannot working normally with oh-my-zsh

### ISSUE THREAD

**Issue by johnwatsondev** [zsh-users/zsh-completions#427]
OS Version: OS X EI Capitan 10.11.5

iTerm2 : Build 3.0.0

Oh-My-Zsh: input `upgrade_oh_my_zsh` just show below info:

```
From https://github.com/robbyrussell/oh-my-zsh
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
```

Zsh Version: zsh 5.2 (x86_64-apple-darwin15.5.0)

Install with oh-my-zsh: follow this [mechanism](https://github.com/zsh-users/zsh-completions#oh-my-zsh)

zsh-completion install path: `~/.oh-my-zsh/custom/plugins/zsh-completions`

---

Here is my [.zshrc](https://gist.github.com/johnwatsondev/6382ec146e9f80e98c677a0c62956f61) file

My shell screenshot is below when I input `gem` and pressed Tab :

![zsh_completion_error](https://cloud.githubusercontent.com/assets/12760754/16065980/fb306d38-32e1-11e6-80cc-287d61a66d54.jpg)

Please let me know if I missed some file or config?

Thanks for the feedback.

**Comment by JonasGroeger** [comment]
For me this works:
    git clone https://github.com/zsh-users/zsh-completions ~/.oh-my-zsh/custom/plugins/zsh-completions
    rm -f ~/.zcompdump; compinit

**Comment by johnwatsondev** [comment]
@JonasGroeger Thanks. I don't know what's wrong with my config. :(

**Comment by JonasGroeger** [comment]
I don't know either :) I'm running on Ubuntu though.
