### ISSUE TITLE
Why is the -a option needed for _describe arrays?

### ISSUE THREAD

**Issue by lukechilds** [zsh-users/zsh-completions#432]
Thank you for the [howto](https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org), I've been writing my own completion and it has been extremely helpful. I wondered if you could just answer a quick question.

In this example fro your howto:

```shell
#compdef cmd
local -a options 
options=('-c:description for -c opt' '-d:description for -d opt')
_describe 'values' options
```

Why do you need the `-a`? It works without it on OS X but fails on Linux. It seems like it is maybe telling zsh that the var will be an array but I can do `foobar=('fizz' 'buzz')` without `-a`.

Why does `('-c:description for -c opt' '-d:description for -d opt')` require `-a` but not `('fizz' 'buzz')`?

I've been searching for ages and don't seem to be able to find an answer, any help would be much appreciated.

**Comment by nicoulaj** [comment]
http://stackoverflow.com/a/3532341 ?
You should try to ask your question on zsh-users mailing list.
