### ISSUE TITLE
NetworkManager (nmcli) completions - update

### ISSUE THREAD

**Issue by juriy-zn** [zsh-users/zsh-completions#434]
[NetworkManager](https://wiki.gnome.org/Projects/NetworkManager)'s **nmcli** completions are outdated (5 years old in fact). It is a pretty popular network manager and there has been a lot of changes to **nmcli**. _It needs some love!_

**Comment by Jassob** [comment]
I would be happy to help if someone could point me at the right direction to start (for instance, in which file are the completions defined?)!

**Comment by nicoulaj** [comment]
The `nmcli` completion is maintained directly in the zsh project: https://github.com/zsh-users/zsh/blob/master/Completion/Linux/Command/_nmcli

You can send them a patch on the `zsh-workers` mailing-list (or a pull request on the Github mirror).

**Comment by Jassob** [comment]
Thank you, I will take a look at it when I have some free time to spare
