### ISSUE TITLE
Fabric completion raises errors

### ISSUE THREAD

**Issue by unklphil** [zsh-users/zsh-completions#436]
When autocompleting for fab, I get the following error:

```
_arguments:comparguments:312: invalid argument:
_fab:86: command not found: (--hide=-)--hide=-[comma-separated list of output levels to hide]: :->levels
```

It still does the completion though.

Initially reported here: https://github.com/robbyrussell/oh-my-zsh/issues/5134 but I think this is where it should be reported

**Comment by nicoulaj** [comment]
Solved by #436
