### ISSUE TITLE
flatpak completion

### ISSUE THREAD

**Issue by xasx** [zsh-users/zsh-completions#446]
flatpak's popularity is raising and more and more zsh users start to use it.
Therefore some command line convenience would be nice.
Thus, please add support for this application.

There's already a bash completion available:
https://github.com/flatpak/flatpak/blob/master/completion/flatpak

There's already an issue at the flatpak project:
flatpak/flatpak#103

**Comment by bil-elmoussaoui** [comment]
I've created a simple plugin here https://github.com/bil-elmoussaoui/flatpak-zsh-completion not perfect, but i will try to improve it as much as possible!

**Comment by okapia** [comment]
flatpak apparently now comes with a zsh completion. Not a great one perhaps but a completion nonetheless.
