### ISSUE TITLE
Yaourt completion

### ISSUE THREAD

**Issue by slavaGanzin** [zsh-users/zsh-completions#457]
Hello. 
Find your project today and already in love with it.

Yaourt completion works well without long parameters:

``` shell
$ yaourt -Rns <tab>
(package list)
```

But fails with them:

``` shell
$ yaourt --noconfirm -Rns <tab>
(nothing)
```

Any clarifications appreciated

Thanks

**Comment by nicoulaj** [comment]
Indeed...

**Comment by DX37** [comment]
And still not enough completions to install packages from AUR.

**Comment by nicoulaj** [comment]
yaourt is EOLed now, closing.
