### ISSUE TITLE
Using a global license by default for the repo?

### ISSUE THREAD

**Issue by blueyed** [zsh-users/zsh-completions#460]
Thanks for bringing up https://github.com/zsh-users/zsh-completions/issues/207 and fixing it.

What do you think about using a global license for the project, which would be the default for files without a license header then?
The short license name might still be used in the files then, but it feels a bit bloated to have (mostly the same?!) license copied in every file.

Or does this complicate things for PRs etc?

/cc @arcan1s @nicoulaj

**Comment by nicoulaj** [comment]
We want contributors to be able to choose the license for the contributions (BSD, ASL, MIT, etc).
And even if we had only one license, each file still would have a license header, so it would not change much.
