### ISSUE TITLE
Improve "apt" completion

### ISSUE THREAD

**Issue by GlebWork** [zsh-users/zsh-completions#467]
zsh lacks some completions like "apt dist-upgrade"

**Comment by syohex** [comment]
`zsh-completions` does not provide `apt` completion. It is provided by zsh itself. Please report official ML.

**Comment by syohex** [comment]
I checked latest source code, it supports new options like `dist-upgrade`.

**Comment by GlebWork** [comment]
that is strange, but thank you!
