### ISSUE TITLE
ag completion needs updating

### ISSUE THREAD

**Issue by ViktorHaag** [zsh-users/zsh-completions#473]
the silver searcher (ag) has gone past version 1.0, and so the stuff in the ag completions plugin that does version-based options checking is now broken. I tried to provide a PR that would fix things, but I think I only succeed in breaking things: someone who understands zsh scripting better than me should probably take on this issue. 8(

**Comment by nicoulaj** [comment]
Related: #471, #472

**Comment by syohex** [comment]
Should we support multiple versions ? I thinks it makes maintenance difficult(like this issue). I suppose it is enough to support only latest version like other completions.

**Comment by okapia** [comment]
The silver searcher comes with a zsh completion of it's own. Why duplicate the work?

**Comment by syohex** [comment]
zsh-completions supports ag completions before the silver searcher has its own zsh completion file. However it should be removed from this repository by our rules.
