### ISSUE TITLE
Request for package(s) for Debian derivatives

### ISSUE THREAD

**Issue by David-Noble-at-work** [zsh-users/zsh-completions#475]
Specifically I would like to install the zsh-completions package to my Debian (x86_64), Ubuntu (x86_64), and Armbian (arm64) systems running zsh 5.2.x.

**Comment by z0rc** [comment]
This have to be filled as a [RFP](https://wiki.debian.org/RFP) in Debian BTS. I don't think that maintainers of this repository should do the packaging. Filling the RFP gives a chance that some Debian developer might be interested in creating package. Or you can always create and submit package [by yourself](https://wiki.debian.org/DebianMentorsFaq#How_do_I_make_my_first_package.3F).

**Comment by David-Noble-at-work** [comment]
I found the deb package elsewhere. You might find the URL and include it on your site one day--or not.

Sent from my iPhone

On Dec 20, 2016, at 3:04 AM, Igor Urazov <notifications@github.com<mailto:notifications@github.com>> wrote:


This have to be filled as a RFP<https://wiki.debian.org/RFP> in Debian BTS. I don't think that maintainers of this repository should do the packaging. Filling the RFP gives a chance that some Debian developer might be interested in creating package. Or you can always create and submit package by yourself<https://wiki.debian.org/DebianMentorsFaq#How_do_I_make_my_first_package.3F>.

-

**Comment by nicoulaj** [comment]
What do you mean ? I did not find the URL you are talking about.

There is no officially maintained zsh package for Debian, see [here](https://packages.debian.org/search?keywords=zsh&searchon=all&suite=all&section=all).

**Comment by David-Noble-at-work** [comment]
Have a closer look.

Sent from my iPhone

On Dec 20, 2016, at 8:59 AM, nicoulaj <notifications@github.com<mailto:notifications@github.com>> wrote:


What do you mean ? I did not find the URL you are talking about.

There is no officially maintained zsh package for Debian, see here<https://packages.debian.org/search?keywords=zsh&searchon=all&suite=all&section=all>.

-

**Comment by nicoulaj** [comment]
Is this guy for real ?

**Comment by nicoulaj** [comment]
Anyway @z0rc gave the correct steps to follow. I'm not using a Debian-based distro myself, so if someone else wants to do it, it would be nice.

**Comment by shirishag75** [comment]
I can file an RFP provided I get the following info -

```
Subject
Package: wnpp
Severity: wishlist

* Package name    : zsh-completions 
  Version         : 0.22.0
  Upstream Author : Name <somebody@example.org>
* URL             : http://www.example.org/
* License         : (GPL, LGPL, BSD, MIT/X, etc.)
  Programming Lang: (C, C++, C#, Perl, Python, etc.)
  Description     : Fish-like fast/unobtrusive autosuggestions for zsh.
```

Usually most of these questions are answered by a copyright or license file. Unfortunately, zsh-completions doesn't have it. 

Can this be fixed ?

**Comment by nicoulaj** [comment]
License in this project is on a per-file basis, so there will never be a top level `COPYING` file.

Here are the licenses used (using [ninka](http://ninka.turingmachine.org) with command `find src -regextype egrep -regex '.*/_[^\\.]+' -exec ninka {} \; | cut -d ';' -f 2 | sort | uniq`):
* Apache v2
* MIT / X
* MIT / BSD variant
* 3-clause BSD

For other fields:
 * Upstream info: `zsh-completions contributors <https://github.com/zsh-users/zsh-completions>` or `Julien Nicoulaud <julien.nicoulaud@gmail.com>` in case an indivdual contact is mandatory
 * URL: `https://github.com/zsh-users/zsh-completions`
 * Programming Lang: `Shell` or `Zsh`
 * Description: `Additional completion definitions for Zsh.`

**Comment by shirishag75** [comment]
Thank you, Filed bugs.debian.org/849878 with above help.

**Comment by nicoulaj** [comment]
In the meanwhile, I created packages on OpenSUSE's build service for many distros (see 907cba3fd9ba16020f55b06b47a86209352652d4)
