### ISSUE TITLE
`brew cask update` is being deprecated

### ISSUE THREAD

**Issue by vitorgalvao** [zsh-users/zsh-completions#484]
As a heads up, [`brew cask update` is being deprecated](https://github.com/Homebrew/brew/pull/1690), so it should be removed from completions. See https://github.com/caskroom/homebrew-cask/issues/26921 for context.

**Comment by syohex** [comment]
`brew` completion was removed from this repository(https://github.com/zsh-users/zsh-completions/commit/173ae7249a6ab4a5b70bebb283f3f156eb79f90). `brew` completion is hosted in official brew repository now(https://github.com/Homebrew/brew/tree/master/completions/zsh).
