### ISSUE TITLE
Request for addition of new rclone zsh-completion

### ISSUE THREAD

**Issue by i3wm** [zsh-users/zsh-completions#485]
Rclone is a command line program to sync files and directories to and from

- Google Drive
- Amazon S3
- Openstack Swift / Rackspace cloud files / Memset Memstore
- Dropbox
- Google Cloud Storage
- Amazon Drive
- Microsoft One Drive
- Hubic
- Backblaze B2
- Yandex Disk
- The local filesystem

I searched the internet before posting here to find if there are already any duplicates available. As I couldn't find any, I would like to request the inclusion of this script for rclone.

    #compdef rclone

    _rclone() { 

	    local state
	    _arguments \
		    '1: :->subcommand' \
		    '--bwlimit' \
		    '--checkers' \
		    '(-c --checksum)'{-c,--checksum}'[check the file hash and size to determine if files are equal]' \
		    '--config' \
		    '--contimeout' \
		    '--dedupe-mode' \
		    '(-n --dry-run)'{-n,--dry-run}'[Do a trial run with no permanent changes]' \
		    '--ignore-existing' \
		    '--ignore-size' \
		    '(-I --ignore-times)'{-I,--ignore-times}'[unconditionally upload all files regardless of the state of files on the destination]' \
		    '--log-file' \
		    '--low-level-retries' \
		    '--max-depth' \
		    '--modify-window' \
		    '--no-gzip-encoding' \
		    '--no-update-modtime' \
		    '(-q --quiet)'{-q,--quiet}'[as little output as possible]' \
		    '--retries' \
		    '--size-only' \
		    '--stats' \
		    '--delete-' \
		    '--timeout' \
		    '--transfers' \
		    '(-u --update)'{-u,--update}'[skip any files which exist on the destination and have a modified time that is newer than the source file]' \
		    '(-v --verbose)'{-v,--verbose}'[tells you about every file it considers and transfers]' \
		    '--delete-excluded' \
		    '--filter' \
		    '--filter-from' \
		    '-exclude' \
		    '--exclude-from' \
		    '--include' \
		    '--include-from' \
		    '--files-from' \
		    '--min-size' \
		    '--max-size' \
		    '--min-age' \
		    '--max-age' \
		    '--dump-filters' \
		    '*:files:_files'
		
	    case $state in
		    subcommand)
			    _arguments '1: :(
				    config
				    copy
				    sync
				    move
				    delete
				    purge
				    mkdir
				    rmdir
				    check
				    ls
				    lsd
				    lsl
				    md5sum
				    sha1sum
				    size
				    version
				    cleanup
				    dedupe
				    authorize
				    cat
				    genautocomplete
				    gendocs
				    listremotes
				    mount
				    --help)'
		    ;;
	    esac
    }
 
    _rclone "$@"

**Comment by nicoulaj** [comment]
Hi, can you take a look at our [contributing guidelines](https://github.com/zsh-users/zsh-completions#contributing) at submit it as a pull request ?
