### ISSUE TITLE
OpenSSH 7.3 "Include" directive not followed for completions.

### ISSUE THREAD

**Issue by StephenBrown2** [zsh-users/zsh-completions#498]
Since OpenSSH 7.3, users can now include files from their main SSH config file.

Release notes https://www.openssh.com/txt/release-7.3
> New Features
> 
> ssh(1): Add an Include directive for ssh_config(5) files.

Unfortunately, the current completion knows nothing of this, and so ignores "Included" files.

This has already been requested as a feature add to OMZ:
REF: https://github.com/robbyrussell/oh-my-zsh/issues/5662
REF: https://github.com/robbyrussell/oh-my-zsh/issues/5788

But I figured it'd be better/a good idea to open an issue here.

**Comment by nicoulaj** [comment]
ssh completion is included in the zsh project, you can submit your request on zsh-workers@zsh.org.
