### ISSUE TITLE
command not found: _arguments

### ISSUE THREAD

**Issue by gfpacheco** [zsh-users/zsh-completions#504]
I'm having trouble with completions for some commands. When I type `vim ` and press tab I get this error:

```
➜ ~ vim _vim:101: command not found: _arguments
_vim:101: command not found: _arguments
_vim:101: command not found: _arguments
```

This also happens with other commands (like `rm`, `cp`, `ls`, `cat`, `grep`):

```
➜ ~ rm _rm:43: command not found: _arguments
_rm:43: command not found: _arguments
_rm:43: command not found: _arguments
```

But not with `mv` or `cd` for example.

One thing I discovered is that I after run `zsh` everything works just fine, but only for this session. When I open another zsh window I got the error again.

Looks like the `_arguments` wrapper function is not being defined.

Any idea of what could be causing the error or how to solve it?

**Comment by nicoulaj** [comment]
This is not the right place for zsh support, try zsh-users@zsh.org or #zsh on freenode.
