### ISSUE TITLE
tox completion

### ISSUE THREAD

**Issue by gaborbernat** [zsh-users/zsh-completions#533]
tox is a python based tool. So I would like to add tox completion (I'm on the tox dev team). Most of the arguments are just fine as they come from _gnu_generic , however for the ``-e`` argument I'll need to provide a line from the output of ``tox -a`` (this information is available only by calling the tool itself).  Any advice how this should be done? Also does this belongs to this user repository? thanks

**Comment by gaborbernat** [comment]
@nicoulaj any feedback related to this?

**Comment by msva** [comment]
I'm not the @nicoulaj, but if you're a part of the upstream, why don't you implement it on your side?

**Comment by nicoulaj** [comment]
@gaborbernat you can find many examples of this in this project or zsh, look for `_call_program`.
Also we usually do not mix up `_gnu_generic` with custom completions, so we just put all the options.

> Also does this belongs to this user repository?
The preferred way is to submit it directly to the zsh project, or have it in your project and make sure packagers deploy it to the right place, or have it there. This project is just a collection that grew up organically, at some point we should clarify the situation with upstream zsh.

**Comment by gaborbernat** [comment]
@nicoulaj Python modules are usually installed with pip which has no knowledge of the shell; so I don't think it makes sense to have this part of the project. This is bound more closely to the shell I feel like.

**Comment by nicoulaj** [comment]
This is not really the issue, you don't even need to have a shell installed to deploy shell completion files for said shell. At worst this adds a useless file to your package.

However, the issue with pip is that it does not handle deployment of files to directories owned by root, so it breaks `pip install --user`/virtualenv... (see for example [in my project](https://github.com/nicoulaj/rainbow/blob/master/setup.py#L63))
