### ISSUE TITLE
[Yarn] Unable to correct completion if script name contains `:`.

### ISSUE THREAD

**Issue by ktrysmt** [zsh-users/zsh-completions#534]
for example, when defined a npm-script as `build:prod`, the completion put out `build -- prod` there.
In the case, `prod` is interpreted as a hints. 
because, ":" is interpreted as a delimiter separating script names and hints.

**Comment by svvac** [comment]
Edit `_yarn_commands_scripts` and `_yarn_scripts` to add a pipe through `sed`: `... | sed -e 's/:/\\:/g'`

    scripts=($(yarn run --json 2>/dev/null | sed -E '/Commands available|possibleCommands/!d;s/.*Commands available from binary scripts: ([^"]+)".*/\1/;s/.*"items":\[([^]]+).*/\1/;s/[" ]//g' | tr , '\n' | sed -e 's/:/\\:/g'))

**Comment by MoOx** [comment]
Hope your fix will be merged soon :)
