### ISSUE TITLE
gcloud does not work when this is activated

### ISSUE THREAD

**Issue by neumachen** [zsh-users/zsh-completions#539]
I just realized when I have this activated, my `gcloud` completion does not work. Any thoughts on this?

**Comment by Dannyzen** [comment]
@magicalbanana I noticed this too. Crazy idea, trying sourcing completion.zsh.inc in your .zshrc. LMK results!

**Comment by Dannyzen** [comment]
I'd actually like to get the completion.zsh.inc added to this repo. Going to do some digging to find someone who can provide me a reliable upstream source that could be automated in the future. ultimately, i'd like to avoid maintaining a completion that's out of date from the binary if i can.

**Comment by okapia** [comment]
It'll need more information than this to reproduce your problem. Neither zsh nor this repository provide any completion for gcloud so what gcloud completion do you have configured and where did you get it from? An what exactly do you mean by "does not work"?

**Comment by magicalbanana** [comment]
@Dannyzen it does work, but after removing `zsh-completions`. If it's loaded, it doesn't work. For your reference @okapia.

**Comment by Dannyzen** [comment]
@magicalbanana @okapia did some experimenting on [my fork](https://github.com/dannyzen/zsh-completions) and if `gcloud` were to be pulled in it would have to be completely re-written. Looking at the src shows that it seems to be using [argcomplete](https://github.com/kislyuk/argcomplete) rather then the standard zsh compdef which we all know and love here. With that said, my vote is that given the unique nature of the autocomplete plugin, it is outside of my understanding and thus, not something I can support.

With that said, you want the autocomplete functionality. NOT GREAT but... It may be easiest to alias `src $PATH_TO/completion.zsh.inc` to an alias of your choice.

**Comment by Dannyzen** [comment]
Of note: "Using completion.zsh.inc may slow down zsh startup." via https://issuetracker.google.com/issues/37819959
