### ISSUE TITLE
patsubst GNU Make targets not completing

### ISSUE THREAD

**Issue by segersniels** [zsh-users/zsh-completions#541]
In `bash` with `bash-completion` installed you are able to autocomplete `patsubst` targets like so:

![bash](https://i.gyazo.com/e3280a1571458599e13ba377b738d299.png)

When using `zsh-completions` this just autocompletes to: 

![zsh](https://i.gyazo.com/3eadacfbe9c9c259d3e0e4f74cec1bfb.png)

Is it possible to implement this functionality in `zsh-completions` as well or am I just being stupid and have I missed something? Been using zsh for quite a while now but switched jobs recently and have need of it again and can't see myself moving back to bash any time soon.

All help is appreciated!

**Comment by okapia** [comment]
Note that the make completion is part of zsh itself and not this project.

Both the bash and zsh completions make an attempt at parsing the Makefile to identify targets. I wouldn't have thought completing test-% is especially useful. If you provide an example Makefile an an indication of which targets it might be matching but isn't then I can take a look.

**Comment by segersniels** [comment]
A quick example that was used to get the above results:

```
VARS?=test1 test2 test3

test-all: $(patsubst %, test-%, $(VARS))
test-%:
  echo $*
```

**Comment by okapia** [comment]
Zsh can do that much but it needs to be enabled:

    zstyle ':completion:*:make:*:targets' call-command true

This is not enabled by default because it has to actually call make to do this and with some Makefiles, there can be side-effects: shell commands actually getting run. I seem to remember that it was also somewhat GNU make specific. But try it and see if it works for you.

**Comment by segersniels** [comment]
Thanks so far, it's a step in the right direction. But it seems to add a lot of unwanted information in the autocompletion:

![](https://i.gyazo.com/8c9af27d0468deb8300e5f6efaaf7832.png)

**Comment by segersniels** [comment]
Thanks, it's a step in the right direction but it seems to add a lot of unwanted suggestions now:

![](https://i.gyazo.com/8c9af27d0468deb8300e5f6efaaf7832.png)

**Comment by okapia** [comment]
Those are make variables. Variables are also valid arguments to make. Now you ought to be able to do the following to give targets precedence over variables but that isn't working due to a separate bug. I'll post a fix to the mailing-list shortly. In the general case, tag-order is often the way to deal with unwanted completion suggestions. Sometimes the ignored-patterns style is more suitable.

    zstyle ':completion:*:make::' tag-order targets variables

You may find it is clearer if you set styles to separate matches for the different tags into separate completion groups and give them a heading:

    zstyle ':completion:*' group-name ''
    zstyle ':completion:*:descriptions' format '%B%d%b'

**Comment by okapia** [comment]
Just occurred to me that even with the unpatched _make you can disable completion of variables with just:

    zstyle ':completion:*:make::' tag-order targets

**Comment by segersniels** [comment]
Another update.

```
zstyle ':completion:*' group-name ''
zstyle ':completion:*:descriptions' format '%B%d%b'
```

Seems to work as described, but is still not exactly what I'm looking for.

![](https://i.gyazo.com/75efb7396e3525d3ba3bb6efc99afbfb.png)

And executing `zstyle ':completion:*:make::' tag-order targets` doesn't seem to do anything for me, the variables stay in place.

**Comment by okapia** [comment]
_make has been updated in zsh git workers/41971, commit 0ebf3364
That should fix tag-order. Unfortunately, that doesn't help you until 5.5 is released and you're able to upgrade. Unless you grab _make from git.

For a short-term workaround, you could use the ignored-patterns style to remove matches consisting of uppercase letters and underscores.

**Comment by segersniels** [comment]
Thanks @okapia, will look forward to version 5.5!

**Comment by segersniels** [comment]
So, 5.5 recently released and was a bit confused as why it still is not working. I still haven't figured out a way to only show the possible targets without the GNU variables showing as well. 

I tried experimenting with `ignored-patterns` and `matcher-list` but no success yet. I guess I'm stuck with the grouped targets a little longer.
