### ISSUE TITLE
$_ doesn't complete

### ISSUE THREAD

**Issue by AndrewSB** [zsh-users/zsh-completions#553]
I'm not sure if this package is supposed to provide this functionality, but in my shell `$_` isn't being replaced by the last command. Other common bashism (like `!!`) are.

If there is a change that can be made here to support that, I'd be more than happy to make it. Just point me in the right direction 🙃

**Comment by nicoulaj** [comment]
This is not the right place for general zsh support, please see:

* http://zsh.sourceforge.net/Doc/Release/zsh_toc.html
* http://zsh.sourceforge.net/Arc/mlist.html
