### ISSUE TITLE
go completion is not loaded

### ISSUE THREAD

**Issue by jshort** [zsh-users/zsh-completions#555]
Something screwy is going on with my OMZ env using zsh-completions as a plugin.  Lots of the zsh-completions work with my setup, but it seems that the `_go` file is not read.  Even if I force it with 

`compdef _go go`

the `_go` function it finds is in:

/usr/local/Cellar/zsh/5.4.2_3/share/zsh/functions/_go

Since that is earlier in my `fpath`.

Is anyone else having problems with the golang completion?

**Comment by jshort** [comment]
If I just delete `/usr/local/Cellar/zsh/5.4.2_3/share/zsh/functions/_go` then it works fine*.  

Can some explain how `compinit` and `fpath` logistics work?

My hunch (after a cursory read of the completion documentation) is that `autoload -U compinit` finds compint script on fpath and then it gets run which scans all of the directories on fpath for files starting with _ and if they have a #compdef on line 1, it runs `compdef` on them.  Since OMZ runs compinit and then I run it against in my zshrc, there must be some logic that if it finds another file (_go in this case) that has already been loaded, it just skips it?  Because the other completions are working (tested with vagrant and jq).

* Actually when the _go in zsh-completions is loaded, I get all sorts of zsh-syntax-highlighting errors.  If I put the original /usr/local/Cellar/zsh/5.4.2_3/share/zsh/functions/_go back in its place, then it is fine:

```
 ✔  jwshort@jwshort-mac  ~ 
 ❯ go version                                                                           10:02:42  03.08.18  63% (4:02) ▆
go version go1.10 darwin/amd64
 ✔  jwshort@jwshort-mac  ~ 
 ❯ f                                                                                    10:02:47  03.08.18  63% (4:02) ▆
_zsh_highlight_main__type:22: bad math expression: operand expected at `/Users/jws...'
 ✔  jwshort@jwshort-mac  ~ 
 ❯ ./                                                                                   10:02:49  03.08.18  63% (4:02) ▆
_zsh_highlight_main__type:22: bad floating point constant
```

As long as I don't cause _go to be autoloaded via a go completion, then the shell and zsh-syntax-highlighting works fine.

**Comment by okapia** [comment]
The `fpath` array contains a list of directories to be searched for _autoloadable_ functions. It starts out initialised to directories containing the functions that come with zsh, which includes an _go function. To use an autoloadable function you first need to run `autoload _name-of-function_`.

compinit is a function that enables a shell-function based completion system. It searches $fpath for files starting with _ or comp and autoloads them based on #compdef or #autoload directives on the first line. The result of this is cached in a file such as `~/.zcompdump`. It was designed to be run once only from `.zshrc`. If you have your own completion functions, such as from this zsh-completions project, you should modify `$fpath` _before_ running compinit else you need to manually autoload them and enable them with compdef.

 Most problems stem from frameworks such as oh-my-zsh. Often they run compinit twice. If $fpath gets modified between runs of compinit, the cache get invalidated so startup is really slow. Things also get messy if there are alternative implementations of a single completion function as with go. So take care of the order of any commands. And my real advice would be not to use oh-my-zsh. Take those parts of it you like and use by all means but but them in your own `.zshrc` without all stuff you never use.

You can see what functions are found first: print -l $fpath/_go(N)
View the contents of a function: functions _go
Force immediate autoloading without running a function: autoload +X _go

**Comment by jshort** [comment]
I decided to remove OMZ from the equation and set the fpath manually to put the zsh-completions `src` folder in the front of fpath and then there is no issue.  Despite the fact that `zsh/5.4.2_3/share/zsh/functions/_go` hasn't been touched in 7 years and likely is unused by anyone, I highly doubt that the zsh maintainers will just remove/rename it.  

Though maybe to get this to work we could rename `_go` in zsh-completions to `_golang` and get rid of the `function _go()` definition and call to `_go`.  It seems that if a `#compdef` file simply is a script, compinit wraps it in a function named for the filename.  Then there would be no collision with the _go file in the zsh distribution.
