### ISSUE TITLE
How do I add a custom completion script for a python script (pack.py for example)

### ISSUE THREAD

**Issue by AllegroDvt** [zsh-users/zsh-completions#559]
I want to add a a custom completion script for one of my scripts (pack.py) If rename it pack and create a custom completion script _pack then it works, but if I use pack.py and _pack.py then the completion script isn't used.
What kind of convention should I use to make it possible to complete this pack.py script ?

Thanks in advance.

**Comment by okapia** [comment]
What you call it is mostly irrelevant. You have to put a special `#compdef` directive on the first line. For example:

    #compdef pack.py

You then need to make sure that the function is in a directory that is in $fpath when you run compinit.

The reason why it works with the name pack is that zsh already comes with a function named _pack. pack was the name of a compression utility on Unix systems. You don't see it too often now but the completion function is still there.

**Comment by AllegroDvt** [comment]
Hi,
I'm not sure what's not right in my setup.
```$ echo $FPATH
/home/tic/bin/zsh_completion:/home/tic/.oh-my-zsh/plugins/colorize:(lot of other oh-my-zsh completion)
```
```$ cat ~/bin/zsh_completion/_pack_py                                                                                                                                                                       
#compdef ./pack.py

local arguments

arguments=(
        {-h,--help}'[show this help message and exit]'
        '*:filename:_files'
        )

_arguments -s $arguments```

If I do:
```
cp ~/bin/zsh_completion/_pack_py ~/bin/zsh_completion/_kpo
unfunction _pack.py; autoload -U _pack.py
./kpo -- -> completion works
```

This is strange as this means the filename is used to know when to use the completion function as the #compdef ./pack.py remains the same inside the _kpo file.

**Comment by okapia** [comment]
The filename is not used. You can check what is used with, e.g:

    print $_comps[kpo]

You should only use the base name of the program in the `#compdef` directive, just:

    #compdef pack.py

Putting `./` in there won't help, regardless if that is how you invoke pack.py.

oh-my-zsh adds a lot of complexity which doesn't help. I think it runs `compinit` twice which is not clever. Make sure you setup $fpath early in .zshrc.

**Comment by AllegroDvt** [comment]
Thanks for the advice and the useful $_comps.
I put the $fpath at the very top of my .zshrc. The completion script still isn't detected the first time i launch a shell, but sourcing my .zshrc a second time makes it work and then it is cached for other session and all is well.
I'm not sure why I get this behavior, but it works for my purpose so thanks a lot.
