### ISSUE TITLE
SVN 1.10.0 complement is not work

### ISSUE THREAD

**Issue by caryhou** [zsh-users/zsh-completions#571]
when i type svn then click tab, I got "_svn:33: bad set of key/value pairs for associative array"
SVN version : 1.10.0 (r1827917)
zsh-completions: stable 0.27.0, HEAD

**Comment by okapia** [comment]
The subversion completion comes with zsh itself and has nothing to do with this project.

On about line 36, it parses the output of svn help to get the list of commands. The line is something like the following. Does this fail for you? If so, what does it produce?

    print -l ${=${(f)${${"$(svn help)"#l#*Available subcommands:}%%Subversion is a tool*}}/(#s)[[:space:]]#(#b)([a-z-]##)[[:space:]]#(\([a-z, ?]##\))#/$match[1] :$match[1]${match[2]:+:${${match[2]//[(),]}// /:}}:}

**Comment by caryhou** [comment]
@okapia thanks for you response. I have not idea the line 36 in which file?

**Comment by smarteng** [comment]
![image](https://user-images.githubusercontent.com/663786/41329415-1be31b8c-6f00-11e8-973f-75a7fc51dba9.png)

**Comment by Jayatubi** [comment]
How does this issue get fixed? I updated zsh to 5.6.2 but the issue still remain.
