### ISSUE TITLE
what is the difference between oh-my-zsh default plugins and zsh-completions?

### ISSUE THREAD

**Issue by Baneeishaque** [zsh-users/zsh-completions#589]
**oh-my-zsh default plugins (need to manually activate - and zsh-completions can also use as a oh-my-zsh plugin) contains auto completion for several tools, and zsh-completions too. which will prefer in case of a particular tool is available in both configurations?** or **_configuring auto completion for a particular tool in both zsh-completions and oh-my-zsh may cause any problems?_** or do you prefer zsh-completions over oh-my-zsh plugins or vice versa? and last **is it good to configure both zsh-completions and oh-my-zsh and use only oh-my-zsh plugins which are not available in zsh-completions and vice versa?**

**Comment by okapia** [comment]
The precedence for completion functions depends on the $fpath array and which directory a particular function will be found in first. Having more than one function for the same tool can cause problems if there are subtle differences in the way the #compdef lines are constructed or if the functions are named differently but in most cases, though you may not have the best completion enabled, it will just work. Many of the completions included with oh-my-zsh are copies of those maintained by the upstream developers of the tool, e.g. _cargo, the intention being to ensure they get installed. Where completions are duplicated, I would tend to assume that those distributed with zsh itself are the best, followed by zsh-completions and that those from oh-my-zsh are the worst but in individual cases, it may be different.

If you don't want things breaking in odd ways, I'd recommend you steer clear of oh-my-zsh entirely. Other than perhaps copying limited parts into your own .zshrc.
