### ISSUE TITLE
zsh compctl  with fallback

### ISSUE THREAD

**Issue by arodus** [zsh-users/zsh-completions#602]
Hey, Is there any way to let a programmable completion fall back to path completion? E.g., if the `dotnet` process doesn’t return any completion suggestions (https://github.com/dotnet/cli/blob/7af1d28dd72fb933966e6201414dc8df6753fcd3/scripts/register-completions.zsh#L3-L8).

**Comment by nicoulaj** [comment]
Hi, please use http://zsh.sourceforge.net/Arc/mlist.html for general zsh support.
