### ISSUE TITLE
"ack foo [tab]" is broken with ack3

### ISSUE THREAD

**Issue by shlomif** [zsh-users/zsh-completions#607]
On Mageia v7:

```
[shlomif@telaviv1 ~]$ ack foo pr
_arguments:comparguments:325: invalid option definition: --xml[.xml .dtd .xsd .xsl .xslt .ent .wsdl; First line matches /<[?]xml/]
[shlomif@telaviv1 ~]$ ack --ver 
_arguments:comparguments:325: invalid option definition: --xml[.xml .dtd .xsd .xsl .xslt .ent .wsdl; First line matches /<[?]xml/]
[shlomif@telaviv1 ~]$ ack --version
ack 2.999_05 (standard build)
Running under Perl 5.28.0 at /usr/bin/perl

Copyright 2005-2018 Andy Lester.

This program is free software.  You may modify or distribute it
under the terms of the Artistic License v2.0.
[shlomif@telaviv1 ~]$ 

```

Please look into fixing it.

**Comment by okapia** [comment]
`ack --help-types` now outputs "First line matches" where before it produced "first line matches".

_ack is one of the completions that used a ZSH licence and so got merged into zsh a little while ago. I've posted a fix to the zsh copy here: https://www.zsh.org/mla/workers/2018/msg01551.html

We can either apply the same patch here, just the first hunk or _ack could be removed from zsh-completions.

You can perhaps workaround the broken function by enabling caching and generating a fixed cache file.

**Comment by shlomif** [comment]
On Thu, 01 Nov 2018 06:04:06 -0700
okapia <notifications@github.com> wrote:

> `ack --help-types` now outputs "First line matches" where before it produced
> "first line matches".
> 
> _ack is one of the completions that used a ZSH licence and so got merged into
> zsh a little while ago. I've posted a fix to the zsh copy here:
> https://www.zsh.org/mla/workers/2018/msg01551.html
> 
> We can either apply the same patch here, just the first hunk or _ack could be
> removed from zsh-completions.
> 
> You can perhaps workaround the broken function by enabling caching and
> generating a fixed cache file.
> 

thanks for the info!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Original Riddles - http://www.shlomifish.org/puzzles/

Mastering ‘cat’ is almost as difficult as herding cats.
    — http://www.shlomifish.org/humour/bits/Mastering-Cat/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by nicoulaj** [comment]
@okapia I missed that, I think these compdefs should be deleted from here since they made it into a zsh tag, no ?

For the record, the commit is https://github.com/zsh-users/zsh/commit/01bc3c124a8c1dc8a5c45f5f5d67bba6e29cabff

**Comment by okapia** [comment]
Yes, I hadn't wanted to remove them in too much of a hurry to give them time to reach a zsh release and to allow a bit of time for people to upgrade. They're in 5.6.

_ansible(-*), _column, _jq, _smartmontools and _shutdown have also been replaced in zsh itself but by rewrites rather than promotions.

Thanks again for having relicenced (and thereby contributed) them.
