### ISSUE TITLE
Add "autoload -U compinit && compinit" to .zshrc or just run once ?

### ISSUE THREAD

**Issue by balalaXD** [zsh-users/zsh-completions#619]
From documentation:
> Enable it in your `.zshrc` by adding it to your plugin list and reloading the completion:
>    ```
>       plugins=(… zsh-completions)
>       autoload -U compinit && compinit
>    ```

If only run once, i think this would be better :)

- Enable it in your `.zshrc` by adding it to your plugin list: 
   ```
      plugins=(… zsh-completions)
   ```
- Reloading the completion:
  ```
      $ autoload -U compinit && compinit
  ```

**Comment by balalaXD** [comment]
You should put this two lines in your `~/.zshrc` file

**Comment by Miever1** [comment]
i think it didn't work

**Comment by Miever1** [comment]
> You should put those two lines in your `~/.zshrc` file

i think it didn't work
