### ISSUE TITLE
_arguments dynamically computed

### ISSUE THREAD

**Issue by grandemk** [zsh-users/zsh-completions#629]
Hi, i was wondering if it was possible to create the arguments to auto complete on the fly by getting the info from the executable we are trying to auto complete.

Here is my try so far.
If I copy what args hold and directly pass that instead of the variable, then the completion works so I'm not sure what I'm missing.

Thanks in advance,
Kevin
```
#compdef _my_func my_exe.exe

_my_func () {

  #  get the options from the exe itself and put them in arrays
  local -a opts=("${(@f)$(my_exe.exe --help-json 2>&1 | al_parse_json.py name)}")
  local -a desc=("${(@f)$(my_exe.exe --help-json 2>&1 | al_parse_json.py desc)}")

  # generate the options descriptions
  args=""
  for ((i = 1; i <= ${#opts}; i++ )) do
    desc_val="${desc[i]}"
    opt_val="${opts[i]}"
    args="$args '${opt_val}[${desc_val}]'"
  done

  args="$args '*:filename:_files'"

  _arguments $args
}
```

**Comment by nicoulaj** [comment]
You should try to ask your question on zsh-users mailing list, this project is not the place for zsh support.

**Comment by grandemk** [comment]
Thanks for the answer, I've changed the way I thought about this problem. I just generate the completion script using the exe --help-json instead of trying to get the options while doing the completion.
