### ISSUE TITLE
How do multiple completions interact? 

### ISSUE THREAD

**Issue by borekb** [zsh-users/zsh-completions#631]
In my `.zshrc`, I've got this:

```bash
# early in the file:
antibody bundle zsh-users/zsh-completions

# later on...
antibody bundle buonomo/yarn-completion
```

Which Yarn completions will win, [these](https://github.com/zsh-users/zsh-completions/blob/cf565254e26bb7ce03f51889e9a29953b955b1fb/src/_yarn) or [these](https://github.com/BuonOmo/yarn-completion/blob/9ba3cfe85ac9f65f703fc4a8df55d7c0f5cf6337/yarn-completion.plugin.zsh)? Is there any interaction between them?

Also, I'd like to try these Bash completions with `bashcompinit` compatibility and I noticed that this project has a [`bashcompinit` file](https://github.com/zsh-users/zsh/blob/5e11082349bf72897f93f3a4493a97a2caf15984/Completion/bashcompinit) which I thought is provided by Zsh itself. Are there any possible conflicts?

I'm asking because I can't get the Bash completions to work and I'm not sure if there's an issue in the compatibility layer somewhere or I'm simply having an incorrect `.zshrc`. For the Bash completions, this is what I'm trying:

```bash
antibody bundle zsh-users/zsh-completions

autoload bashcompinit && bashcompinit
antibody bundle dsifford/yarn-completion path:yarn-completion.bash
```

It does a basic autocompletion so it partially works but some functionality like Yarn workspaces doesn't work: https://github.com/dsifford/yarn-completion/commit/4d4089296c032419968da68e4cf8086b602b51a8#r33148720.

**Comment by okapia** [comment]
It depends on the order in which antibody adds the directories to the fpath array. Run `print -l $fpath` and see what order it includes the relevant directories in.

I'd avoid bashcompinit if at all possible. Bash completion is very much more basic than zsh. You get no descriptions for instance. Bash completions often assume that you've sourced the entire bash_completions project which includes a number of extra functions. Add to that the fact that there are areas where bash and zsh are not compatible. Getting bashcompinit to work for a function is often more trouble than just writing a proper function for zsh.
zsh-users/zsh on github is purely a mirror of the zsh git repository. It is maintained by upstream zsh and upstream zsh (me in this case) monitors both the github and gitlab mirrors for pull requests.
