### ISSUE TITLE
node --prof-process flag doesn't autocomplete *.log files

### ISSUE THREAD

**Issue by reasonablytall** [zsh-users/zsh-completions#633]
The node autocompletion restricts to *.js files which works well for the general use case, but when processing a profile log with `--prof-process` it becomes difficult to complete the *.log files generated by `--prof`.

I'm not sure if the completion system can handle it, but it would be nice if it would switch to completing *.log files when the `--prof-process` flag is passed.

**Comment by syohex** [comment]
I have sent PR #690

**Comment by syohex** [comment]
I've fixed this issue. Please check latest version.
