### ISSUE TITLE
Conflict with official kitty package in Arch Linux

### ISSUE THREAD

**Issue by davidsierradz** [zsh-users/zsh-completions#647]
This package [Arch Linux - kitty 0.14.3-1 (x86_64)](https://www.archlinux.org/packages/community/x86_64/kitty/) already installs a completion file for zsh, trying to install zsh-completions, this happens:

```
error: failed to commit transaction (conflicting files)
zsh-completions-git: /usr/share/zsh/site-functions/_kitty exists in filesystem (owned by kitty)
Errors occurred, no packages were upgraded.
```

I can install zsh-completions with `yay -S --overwrite /usr/share/zsh/site-functions/_kitty zsh-completions-git`, but I think this is a hack.

Thanks!

**Comment by nicoulaj** [comment]
Mhh... The official one has no descriptions, and doesn't even complete filenames after `kitty -c`...

But I guess we have no choice but to remove this one.

**Comment by davidsierradz** [comment]
Maybe talk to @kovidgoyal to improve upstream kitty completion?

Also, `zsh-completions` is not used by other distros? maybe this change will remove kitty completions for them.

**Comment by kovidgoyal** [comment]
I just added support for completing -c https://github.com/kovidgoyal/kitty/commit/415701c58a55892f9a10889b4ac70b4bbaaf6fd2

Not sure what descriptions you are referring to, but patches are most welcome.

**Comment by kovidgoyal** [comment]
And I will note that the upstream completions include completion for kittens and remote control, not just the basic CLI.
