### ISSUE TITLE
Question: Exclude path from completion?

### ISSUE THREAD

**Issue by anthonyclarka2** [zsh-users/zsh-completions#648]
Is there a way to globally exclude a path from all completions?

When `cd`ing into the `/keybase` path hierarchy I get multiple permission denied errors because completion (I think) is trying to scan potential folders as I type.

The `/keybase` path is where Keybase's KBFS is mounted, which allows you access to any user's public files, plus private team files etc.

Thank you for writing this, it makes my command line so much better!

**Comment by syohex** [comment]
Override tab(`Ctrl-i`) command as below.

```bash
function my-tab() {
  if [[ ! $PWD = /keybase* ]]; then
    zle expand-or-complete
  else
    echo -en "\007"
  fi
}

zle -N my-tab
bindkey "^I" my-tab
```

Following link explains about this topic in more detail.

https://superuser.com/questions/585545/how-to-disable-zsh-tab-completion-for-nfs-dirs

**Comment by anthonyclarka2** [comment]
Well thank you very, very much!!!

**Comment by trallnag** [comment]
Nice this is exactly what I was looking for. Also helps with using Zsh in WSL. WSL adds all the Windows PATH entries to Linux PATH and this brings completion with commands like `source` to a complete halt.
