### ISSUE TITLE
GPG Release Key for Debian release expired

### ISSUE THREAD

**Issue by mindsolve** [zsh-users/zsh-completions#657]
Hey everybody!

Since `2019-10-14` the gpg signing key for the Debian/Ubuntu repo is expired and giving errors while refreshing package lists.
Could this be fixed?

Thanks,
MindSolve

**Comment by teoman002** [comment]
I can confirm that the error remains unsolved.

**Comment by Kwaadpepper** [comment]
Could gpg keys be updated ?

**Comment by nicoulaj** [comment]
It should be working now

**Comment by jimblue** [comment]
It's not

**Comment by mindsolve** [comment]
@jimblue: It does work, you just have to manually reimport the certificate.
You can find the instructions for that on the OBS Repository page.

For Ubuntu (16.04-19.10) run:
```bash
wget -nv https://download.opensuse.org/repositories/shells:zsh-users:zsh-completions/xUbuntu_19.10/Release.key -O Release.key
sudo apt-key add Release.key
```
