### ISSUE TITLE
Yarn | `}` character in script command blocks suggestions

### ISSUE THREAD

**Issue by MaximDevoir** [zsh-users/zsh-completions#667]
If the `}` character is part of a script command, the _yarn plugin stops short of processing other scripts commands.

**Example**

Given:

```TypeScript
// package.json
{
 "scripts": {
  "test": "./test.sh",
  "start": "webpack-dev-server --mode development --watch --hot --progress --color --port 3000",
  "build": "rm -rf 'dist/*' && webpack-cli --mode production --progress --color",
  "eslint": "eslint --max-warnings 200 \"src/**/*.{ts,tsx}\"",
  "format-check": "prettier --check \"src/**/*.ts\"",
  "format-fix": "yarn eslint --fix",
  "pretty": "prettier --write \"src/**/*.ts\"",
  "lint": "yarn pretty && yarn eslint"
 }
}
```

Results in:

![Screenshot from 2019-11-02 14-33-54](https://user-images.githubusercontent.com/10104630/68077300-96d8ad80-fd7e-11e9-8a3e-e35ef1bfe69f.png)

**Comment by MaximDevoir** [comment]
cc/ @mcornella Do you think you could take a look at this? My sed regular expression skills aren't so great.

The issue seems to be coming from `.*"hints":\{([^}]+)\}.*` 
https://github.com/zsh-users/zsh-completions/blob/8def5f15835f294ec6a1bf220fb330efddbe2575/src/_yarn#L91

**Comment by mcornella** [comment]
The `hints` property always ends with a double quote, so we can substitute `([^}]+)\}` for `(.+")\}` meaning, match anything until a double quote and a closing curly brace, including the double quote in the captured group. The only way I can see this breaking is if there are other objects under the hints property but I don't see why that should happen.

```diff
diff --git a/src/_yarn b/src/_yarn
index 3689ae9..ce0baef 100644
--- a/src/_yarn
+++ b/src/_yarn
@@ -88,7 +88,7 @@ _yarn_scripts() {
   runJSON=$(yarn run --json 2>/dev/null)
   binaries=($(sed -E '/Commands available/!d;s/.*Commands available from binary scripts: ([^"]+)".*/\1/;s/.*"items":\[([^]]+).*/\1/;s/[" ]//g;s/:/\\:/g;s/,/\n/g' <<< "$runJSON"))
   scriptNames=($(sed -E '/possibleCommands/!d;s/.*"items":\[([^]]+).*/\1/;s/[" ]//g;s/:/\\:/g;s/,/\n/g' <<< "$runJSON"))
-  scriptCommands=("${(@f)$(sed -E '/possibleCommands/!d;s/.*"hints":\{([^}]+)\}.*/\1/;s/"[^"]+"://g;s/:/\\:/g;s/","/\n/g;s/(^"|"$)//g' <<< "$runJSON")}")
+  scriptCommands=("${(@f)$(sed -E '/possibleCommands/!d;s/.*"hints":\{(.+")\}.*/\1/;s/"[^"]+"://g;s/:/\\:/g;s/","/\n/g;s/(^"|"$)//g' <<< "$runJSON")}")
   for (( i=1; i <= $#scriptNames; i++ )); do
     scripts+=("${scriptNames[$i]}:${scriptCommands[$i]}")
```

**Comment by mcornella** [comment]
> The only way I can see this breaking is if there are other objects under the hints property but I don't see why that should happen.

Either way, since sed is greedy by default, a `"}` in an object inside the hints property would be included and match until the very last end of the hints value. This means the proposed solution works even if there is a script that uses the `"}` pair (not often seen in a shell script, but possible).
