### ISSUE TITLE
Provide completion for Kubernetes in Docker (kind)

### ISSUE THREAD

**Issue by RafalSkolasinski** [zsh-users/zsh-completions#673]
It may be a nice idea to provide a completions for [kind](https://kind.sigs.k8s.io/).

**Comment by mwalimu-prog** [comment]
Thank you. Looks awesome👍.

**Comment by syohex** [comment]
@RafalSkolasinski `kind` supports zsh completion by itself. You can generate zsh completion file for `kind` by `kind completion zsh`.

```sh
kind completion zsh > your_zsh_completion_file_directory/_kind
rm ~/.zcompdump
exec zsh
# you can complete kind options
```

We don't support command completion which is available in original project by our policy.

**Comment by leohxj** [comment]
detail installation instructions is here: https://github.com/kubernetes-sigs/kind/blob/main/pkg/cmd/kind/completion/completion.go#L53
