### ISSUE TITLE
Completion for `flutter` is outdated

### ISSUE THREAD

**Issue by drianoaz** [zsh-users/zsh-completions#682]
The support for Flutter cli tool completions was added to zsh-completions in mid-2018 (#565). Since then, several commands have been added in the flutter and these have not been updated.

Example of the new available commands:

  - **assemble**:                 Assemble and build flutter resources.
  - **attach**:                   Attach to a running application.
  - **bash-completion**:          Output command line shell completion setup scripts.
  - **emulators**:               List, launch and create emulators.
  - **pub**:                     Commands for managing Flutter packages.
  - **version**:                 List or switch flutter versions.

**Comment by MaximDevoir** [comment]
Thank you @drianoaz for bringing this to our attention. I'm not familiar with the Flutter CLI. Do you think you would like to work on that?

**Comment by drianoaz** [comment]
Yes, I would like to work on that. In the next few days, I will open a PR.

**Comment by syohex** [comment]
I have merged #754. Please check latest version.
