### ISSUE TITLE
Each reboot requires a compinit run.

### ISSUE THREAD

**Issue by cathaysia** [zsh-users/zsh-completions#684]
Hello!
Thanks for your work on zsh. Now I find I need a compinit run after each reboot.

All of information at here:
---
System: ArchLinux
ZSH Path: /etc/oh-my-zsh
zsh-completions: /etc/oh-my-zsh/plugins/zsh-completions
plugins=(git sudo zsh-autosuggestions zsh-completions)
---
I want a completion of firewalld, it works. But I need  a compinit each reboot.
How I fix this problem?

**Comment by bwoodruff** [comment]
I'm seeing this each time a launch a new terminal instance. Running compinit manually it works, but I have 

```
plugins=(git zsh-completions zsh-syntax-highlighting)
autoload -U compinit && compinit
source $ZSH/oh-my-zsh.sh
```

in my .zshrc? I also tried:

```
plugins=(git zsh-completions zsh-syntax-highlighting)
fpath=($ZSH/custom/plugins/zsh-completions/src $fpath)
autoload -U compinit && compinit
source $ZSH/oh-my-zsh.sh
```

with the same result

**Comment by kuasha420** [comment]
@bwoodruff  Put `autoload -U compinit && compinit` after `source $ZSH/oh-my-zsh.sh
`
