### ISSUE TITLE
Go completion causing segfault

### ISSUE THREAD

**Issue by keynan** [zsh-users/zsh-completions#686]
Apologies for the lack of details. I'm rather new to completions. I copied the _golang completion to my local completion dir and "go <tab>" caused terminal to exit with SEGSEV.

Ubuntu 18.04 
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

**Comment by keynan** [comment]
cc: @markcornick

**Comment by syohex** [comment]
I cannot reproduce this issue. Could you show us how to reproduce this issue in more detail ? And could you retry after removing `~/.zcompdump` file ?

**Comment by syohex** [comment]
I cannot also reproduce this issue with same zsh version(5.4.2)
