### ISSUE TITLE
Add completions for Flameshot

### ISSUE THREAD

**Issue by bwoodruff** [zsh-users/zsh-completions#687]
Please consider adding completions for Flameshot. zsh on the left, bash on the right:

![bash vs zsh completion](https://user-images.githubusercontent.com/553522/76721121-48b4bd00-6715-11ea-92bb-6572ee2f35ce.png)

**Comment by mwalimu-prog** [comment]
Ok thanks

**Comment by syohex** [comment]
@bwoodruff I have merged PR. Please check latest version.

**Comment by bwoodruff** [comment]
Thank you @syohex!

**Comment by syohex** [comment]
@bwoodruff Sorry we had removed flameshot completion file(#764) because flameshot now provides its own completion file. So please use official version instead of this.

Reference
- https://github.com/flameshot-org/flameshot/blob/master/docs/shell-completion/flameshot
