### ISSUE TITLE
Is it possible to execute command on user selection change?

### ISSUE THREAD

**Issue by rodrigogonegit** [zsh-users/zsh-completions#693]
How can I execute a command every time the user changes his selection? For instance when navigating through a long list of suggested values, I want to execute a custom command.
[Something like this. Execute command X onSelectionChange](https://imgur.com/SdgjoBE)
Thank you!

**Comment by syohex** [comment]
I'm not sure that I suppose it imay be possible. However it does not suit for `zsh-completions`. I suppose `fzf` or `peco` suit for your purpose.

- https://github.com/junegunn/fzf
- https://github.com/peco/peco
