### ISSUE TITLE
yarn completions --cwd option support

### ISSUE THREAD

**Issue by bogdan** [zsh-users/zsh-completions#712]
`--cwd=sudirectory` option for yarn changes current working directory. Is it possible to modify completions to support package.json file from the specified subdirectory?

```
yarn --cwd=module1 ins<tab>
```

**Comment by syohex** [comment]
Yes, it is possible. Please wait a few day for supporting that feature.

**Comment by syohex** [comment]
![yarn](https://user-images.githubusercontent.com/554281/81468056-122c8780-9218-11ea-8e25-b2668d339e31.gif)

@bogdan Latest version works like above gif. Please check latest version.
