### ISSUE TITLE
go-get autocompletion fails with "_golang:509: command not found: *:importpaths:__go_packages"

### ISSUE THREAD

**Issue by y34hbuddy** [zsh-users/zsh-completions#745]
When attempting to update a package with "go get -u ...", autocompletion fails and prints the following directly on the command line:

`_golang:509: command not found: *:importpaths:__go_packages`

By manually modifying line 509 from `*:importpaths:__go_packages` to `__go_packages`, this resolves the issue.

OS: Slackware Linux 64-bit -current
Go version: 1.13.10
Zsh version: 5.8
Zsh-completions: commit d3c3df0f2e86f502b00ac06393f7cd1aa94590f6

**Comment by syohex** [comment]
@y34hbuddy  Thanks for reporting issue. I have merged #746. Could you check latest version ?

If you have completions cache, you need to clear cache.

```
rm ~/.zcompdump
exec zsh
```

**Comment by y34hbuddy** [comment]
Thanks, @syohex -- yes, this appears to have resolved the issue.
