### ISSUE TITLE
compinit:503: no such file or directory: /usr/share/zsh/vendor-completions/_docker

### ISSUE THREAD

**Issue by skhaz** [zsh-users/zsh-completions#755]
When I open a new terminal on Ubuntu under WSL2 I got:

```
compinit:503: no such file or directory: /usr/share/zsh/vendor-completions/_docker
```

Any ideias?

**Comment by syohex** [comment]
Its completion file is provided by Docker engine Ubuntu package. So I suppose your issue may be fixed by installing docker engine.

BTW `zsh-completions` does not provide docker completion file. Is it oh-my-zsh plugin issue ? (https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/docker)

**Comment by ElanHasson** [comment]
I use WSL2 also, docker wasn't running.

**Comment by NiceAsiv** [comment]
I didn't even install docker on wsl2, but this error occurred, but I installed it on windows, does it matter?

**Comment by Omico** [comment]
@NiceAsiv Yes, it no longer shows up after I enable this on my Windows.
![image](https://github.com/zsh-users/zsh-completions/assets/14316223/e5bbfe00-80dc-4074-8b8e-76beb2d08e1f)

**Comment by NiceAsiv** [comment]
> @NiceAsiv Yes, it no longer shows up after I enable this on my Windows.
> ![image](https://github.com/zsh-users/zsh-completions/assets/14316223/e5bbfe00-80dc-4074-8b8e-76beb2d08e1f)
> 

Thx a lot⸜₍๑•⌔•๑₎⸝

**Comment by brunofm** [comment]
Can confirm that the above solution worked for me too.

**Comment by jbusodev** [comment]
Any solution to hide this error messages when docker is not running?
