### ISSUE TITLE
view value of variables in a completion function

### ISSUE THREAD

**Issue by blueray453** [zsh-users/zsh-completions#759]
I have [found][1] the following zsh completion function

    #compdef _h h
    
    _h() { 
        local curcontext="$curcontext" state line
     
        _arguments \
            '1: :->country'\
            '*: :->city'
     
        case $state in
        country)
            _arguments '1:Countries:(France Germany Italy)'
        ;;
        *)
            case $words[2] in
            France)
                compadd "$@" Paris Lyon Marseille
            ;;
            Germany)
                compadd "$@" Berlin Munich Dresden
            ;;
            Italy)
                compadd "$@" Rome Napoli Palermo
            ;;
            *)
                _files 
            esac
        esac
    }

I want to see (`echo`) the value of the variables (`$curcontext`,`$state`,`$line` and `$words`) but not sure where or how the output will be shown (as completion function is only triggered when I press <kbd>tab</kbd>).

How can I see the value of the variables mentioned above.

  [1]: https://askql.wordpress.com/2011/01/11/zsh-writing-own-completion/
  [2]: http://zsh.sourceforge.net/Doc/Release/Completion-System.html

**Comment by syohex** [comment]
- add debug statement like `echo "curcontext=$curcontext state=$state line=$line words=$words[@]"` where you want to see those values
- Remove cache file `rm ~/.zcompdump`
- Restart zsh `exec zsh`
- Debugging
  -  You can press tab then debug message displays
- Remove debug statement if you finish debugging

**Comment by blueray453** [comment]
The current output seems like

```
% h curcontext=:complete:h: state= line= words=h curcontext=:complete:h: state= line= words=
France                                                   h curcontext=:complete:h: state= line= words=h curcontext=:complete:h: state= line= words=
France                                                   h France curcontext=:complete:h: state=city line=France  words=h curcontext=:complete:h: state=city line=France  words=France curcontext=:complete:h: state=city line=France  words=

% h Germany curcontext=:complete:h: state=city line=Germany  words=h curcontext=:complete:h: state=city line=Germany  words=Germany curcontext=:complete:h: state=city line=Germany  words=
Berlin                                                   h Germany Berlin curcontext=:complete:h: state=city line=Germany Berlin  words=h curcontext=:complete:h: state=city line=Germany Berlin  words=Germany curcontext=:complete:h: state=city line=Germany Berlin  words=Berlin curcontext=:complete:h: state=city line=Germany Berlin  words=
Berlin                                                   h Germany Berlin Dresden curcontext=:complete:h: state=city line=Germany Berlin Dresden  words=h curcontext=:complete:h: state=city line=Germany Berlin Dresden  words=Germany curcontext=:complete:h: state=city line=Germany Berlin Dresden  words=Berlin curcontext=:complete:h: state=city line=Germany Berlin Dresden  words=Dresden curcontext=:complete:h: state=city line=Germany Berlin Dresden  words=
Berlin                                                   h Germany Berlin Dresden Berlin
Berlin   Dresden  Munich 
```
Is there any way to view the debug output in a separate terminal?

**Comment by syohex** [comment]
Debug print statement redirects to another terminal or file

1. launch 2nd terminal emulator
2. check its `$TTY`. `echo $TTY`
3. change debug statement as below

```bash
echo "curcontext=$curcontext state=$state line=$line words=$words[@]" > device_file_path # like /dev/pts/3
```

Or

1. create output file `touch some_file`
2. change debug statement as below
3. trace the file output by tee command `tee -f some_file` on another shell

```bash
echo "curcontext=$curcontext state=$state line=$line words=$words[@]" >> some_file
```
