### ISSUE TITLE
how to use tags in zsh completion system

### ISSUE THREAD

**Issue by blueray453** [zsh-users/zsh-completions#760]
The [documentation][1] says

>     zstyle ':completion:*:aliens:*' tag-order \ 
>       'frooble:-funny:funny\ frooble' frooble
>which is used when you're completing for the command aliens, which presumably has completions tagged as `frooble' ...

I understand that both context and tag can be viewed using <kbd>^Xh</kbd>. So, I tried the following command but suggestion did not show the tags.

    % zstyle ':completion:*:aliens:*' tag-order 'frooble:-funny:funny\ frooble' frooble 
    % aliens <kbd>TAB</kbd>
    Completing file
    Desktop/       Documents/     dotfiles/      Downloads/ 
    % aliens <kbd>^Xh</kbd>
    tags in context :completion::complete:aliens::
        globbed-files  (_files _default)
    % aliens frooble <kbd>^Xh</kbd>
    tags in context :completion::complete:aliens::
        globbed-files  (_files _default)

I think I am doing something wrong with 

> completions tagged as `frooble'

Please help me understand how to use tags in zsh completion system.

  [1]: http://zsh.sourceforge.net/Guide/zshguide06.html#l155

**Comment by okapia** [comment]
Note that Peter's user-guide is not "_THE_ documentation" only the zsh manual can be so described.

The key problem here is that the fictional aliens command does not have any completions defined with any tags, least of which "frooble". So the example is not standalone. Instead you get default file completion and a tag named "globbed-files" instead. You could define one if it helps:

```
compdef '_wanted frooble expl frooble compadd funny wibble wobble' aliens
```

**Comment by blueray453** [comment]
Thank you very much for helping me out here. However, I need a little more help.

```
% aliens <kbd>^Xh</kbd>
tags in context :completion::complete:aliens::
    frooble  (_normal)
```

So, I guess we have registered one tag.

Now how can we register multiple tags. For example: frooble1, frooble2, frooble3 etc.

What is `_wanted frooble expl frooble ` doing?

And what do we get out of these tags. I read the documentation. However, I do not understand the significance of tags.

For example:

```
% aliens fro<kbd>tab</kbd>
No Matches: `frooble'
```
What is it matching against. What happens if the match is found.

**Comment by blueray453** [comment]
I took suggestion from someone else. He told me to not think about tags for now.
