### ISSUE TITLE
zsh: bad set of key/value pairs for associative array

### ISSUE THREAD

**Issue by Songkunda** [zsh-users/zsh-completions#761]
Before environment:
- bash 5.0
- MacOS 10.14.3

Now environment:
- bash 3.2
- zsh 5.7.1
- MacOS 10.15.6

:
- The TAGS variable is a string
- I want to turn strings into Map types
- I want to get the values in the map by key

Before,i use bash5:
```
TAGS='(["a"]=1 ["b"]=2 ["c"]=3)'
declare -A tag=${TAGS}
NS="a"
declare -x VERSION=${tag[$NS]}
//VERSION 1
```
After upgrading the system,and i Used Zsh:
```bash
// error
TAGS='a 1 b 2 c 3'

local -A tag=($TAGS)
// out :zsh: bad set of key/value pairs for associative array
// The Error is Bug?
```
now, it worked:
```bash
TAGS='a 1 b 2 c 3'
local -A tag=($(echo $TAGS)) // it worked, but not beautiful
NS='a'
version =${tag[${NS}]}

```

it worked, but not beautiful. Who can tell me how to do it.

**Comment by syohex** [comment]
I suppose you should ask zsh mailing lists for this question rather than here.

BTW as far as I read documentation, there is no way except your last snippet.
