### ISSUE TITLE
[INFO] Flameshot will provide its own completions

### ISSUE THREAD

**Issue by TheAifam5** [zsh-users/zsh-completions#762]
Hey, while using the git version of flameshot on AUR I noticed that there is conflict for `_flameshot`.

The change might be in future releases:
https://github.com/flameshot-org/flameshot/commit/23ae6c15796a61a86a4df612dbb1990c19585eda

Best regards,
TheAifam5

**Comment by Feresey** [comment]
anybody here?

**Comment by syohex** [comment]
#764

**Comment by syohex** [comment]
I have merged #764
