### ISSUE TITLE
[Suggest] completion shoud consider statement's context ?

### ISSUE THREAD

**Issue by slarsar** [zsh-users/zsh-completions#766]
considering such a situation:
I have a directory `src` and a executable script `script.sh` in my work dir
![image](https://user-images.githubusercontent.com/46400566/98107970-37076c00-1ed6-11eb-9344-881976a91b81.png)
I cd into src,  then I want to do this ` cd ../ && ./script.sh ` , but zsh didn't complete script when I typed `./s`

**Comment by syohex** [comment]
It is zsh issue, not zsh-completions.
Please send such suggestion to zsh mailing list(http://zsh.sourceforge.net/Arc/mlist.html)

**Comment by slarsar** [comment]
> It is zsh issue, not zsh-completions.
> Please send such suggestion to zsh mailing list(http://zsh.sourceforge.net/Arc/mlist.html)

Thank you.
