### ISSUE TITLE
[Request] Just completions

### ISSUE THREAD

**Issue by vmiheer** [zsh-users/zsh-completions#767]
They are already present [here](https://github.com/casey/just/blob/master/completions/just.zsh). It would be great if they were part of this repository.

**Comment by vmiheer** [comment]
[Oh my zsh PR](https://github.com/ohmyzsh/ohmyzsh/pull/9287)

**Comment by syohex** [comment]
> The compdef is not already available in zsh.
> The compdef is not already available in their original project.

[Our policy](https://github.com/zsh-users/zsh-completions/blob/master/.github/PULL_REQUEST_TEMPLATE.md) is :arrow_up:. We don't add the completion into this repository if it is provided in original repository
