### ISSUE TITLE
It does nothing.

### ISSUE THREAD

**Issue by laichiaheng** [zsh-users/zsh-completions#778]
When I input `sudo pacman -Rs f` and press TAB, it returns nothing.

**Comment by syohex** [comment]
We do not provide the pacman completion file. And it is provided by pacman itself.

https://git.archlinux.org/pacman.git/tree/scripts/completion/zsh_completion.in

It says `# copy this file to /usr/share/zsh/site-functions/_pacman`. Please copy it and retry.

**Comment by laichiaheng** [comment]
Do I need to add something to .zshrc? Or just remove .zcompdump?
How do you know this!

**Comment by syohex** [comment]
> Do I need to add something to .zshrc?

I suppose

- no If you can complete other commands 
- yes you cannot complete any commands at all.

> Or just remove .zcompdump?

You need to remove cache file if you update any complete configurations.
