### ISSUE TITLE
How to change color or make text item list under like zsh-autosuggestions

### ISSUE THREAD

**Issue by scila1996** [zsh-users/zsh-completions#785]
Hi. Current when i press '[TAB]' and it will be show the list under command like this. But color of them is alternative to command 

![image](https://user-images.githubusercontent.com/17109300/110980806-d531a400-8398-11eb-940e-f03b4f3b0ddf.png)

I like all item of under list will colored like zsh-autosuggestions

![image](https://user-images.githubusercontent.com/17109300/110980934-fb574400-8398-11eb-8fd1-47751abaf194.png)

How can i do that , thank all !

**Comment by syohex** [comment]
https://stackoverflow.com/questions/23152157/how-does-the-zsh-list-colors-syntax-work

I'm afraid I don't know. It seems you can change color by `zstyle`, `list-colors`.
