### ISSUE TITLE
CMake completions are practically unusable

### ISSUE THREAD

**Issue by ratijas** [zsh-users/zsh-completions#791]
I'm sorry to say this, but CMake completions provided by this package are really hard to use.

On my system, `cmake -S <Tab>` gives me only option `-E` which zsh immediately applies. Even after manually rewriting that, `cmake -S myProject <Tab>` stops completing anything, even just files/directories. Removing space does not help: `cmake -S<Tab>` doesn't offer any completions either.

### Version

- OS: Linux getaway 5.11.11-arch1-1 #1 SMP PREEMPT Tue, 30 Mar 2021 14:10:17 +0000 x86_64 GNU/Linux
- zsh-completions: 0.32.0-1
- cmake: 3.20.0-1
- zsh: 5.8-1

**Comment by ratijas** [comment]
OK, let me build from the latest. I'll report back soon.

**Comment by ratijas** [comment]
Yes!  Latest changes from master branch really fix the issue. It was around Dec 26, 2020, 63b470243b4edd40eab657752c961d5985d37b09..6dff9453ca1e839427cfd2a618afd752edf5e2bf. Unfortunately, last release (0.32.0) was too long ago: May 26, 2020. How about rolling out a fresh one? :)

**Comment by syohex** [comment]
@nicoulaj Can I tag a new version(0.33.0) ?
