### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by pavel-the-best** [zsh-users/zsh-completions#801]
Since Sep 20 there has been many improvements.
For example, flameshot now ships with its own completions, but zsh-completions in the latest release also provides those completions resulting in file conflict. This was fixed in https://github.com/zsh-users/zsh-completions/commit/2e009c7ab8e9c7496ed86473ede0917a3cefee01, 9 days after the release in September 2020.
Is there anything stopping the release?

**Comment by syohex** [comment]
This repository is not maintained actively.  I have only merge permission and I cannot add new tag.

@nicoulaj Could you add new tag or give me push permission of this repository ?

**Comment by nicoulaj** [comment]
I pushed a 0.33.0 tag and added you to admins team. Sorry for my lack of responsiveness on this project, feel free to publish releases whenever you feel it is needed!
