### ISSUE TITLE
file completion not working with `git log -L`

### ISSUE THREAD

**Issue by bruce-ricard** [zsh-users/zsh-completions#804]
Hi,

apologies if this is not the right place to ask. Posting  in the [git](https://github.com/git/git/blob/master/contrib/completion/git-completion.zsh) repo felt like I wouldn't hit the right audience.

I am having issues with my shell not autocompleting files after typing `git log -L 42,42:<tab>` nothing shows up. Everything else works: autocompleting of files on other commands, e.g. `git log <tab>` shows the files; `git l<tab>` gets "git log". But I cannot get it to work with the `-L` option.

As another example, if I type `git log -L 42,42 <tab>` (notice the space instead of the colon), then it does autocomplete, but for some reason the syntax of this flag is `line,line:file`.

Does this work for other people? If yes, would you have any pointer to help me debug why it isn't working for me? I found the [testing & debugging](https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org#testing--debugging) of zsh completions. I tried hitting the debugger as I had typed `git log -L 42,42:r<tab>` and I get this

>tags in context :completion::approximate-1:git::
    argument-rest  (_arguments __git_zsh_main _git)
    globbed-files  (_files _default _git)
tags in context :completion::approximate:::
    corrections original  (_approximate)
tags in context :completion::complete:git::
    argument-rest  (_arguments __git_zsh_main _git)
    globbed-files  (_files _default _git)
tags in context :completion::correct-1:git::
    argument-rest  (_arguments __git_zsh_main _git)
    globbed-files  (_files _default _git)
tags in context :completion::correct:::
    corrections original  (_approximate)

which I really don't understand how to read.

Please advice, thanks.

**Comment by syohex** [comment]
It seems this issue was fixed with newer zsh.
