### ISSUE TITLE
Can we get cURL completions as well ?

### ISSUE THREAD

**Issue by ShivamJoker** [zsh-users/zsh-completions#807]

**Comment by syohex** [comment]
`curl` provides own [completion generator](https://github.com/curl/curl/blob/master/scripts/completion.pl). You can generate zsh completion file as below.

```bash
perl completion.pl --shell zsh > your_completion_dir/_curl
```

If you are macOS user and install curl by homebrew, generated completion file is `/usr/local/opt/curl/share/zsh/site-functions/_curl`. Linux distribution such as Ubuntu, zsh completion file is installed automatically after `apt install curl`.
