### ISSUE TITLE
_arguments:comparguments:325: can only be called from completion function

### ISSUE THREAD

**Issue by zouxiaoliang** [zsh-users/zsh-completions#809]
This problem appears after updating to the latest version

I solved this by deleting the file 'src/_rmlint.sh '

**Comment by syohex** [comment]
@zouxiaoliang could you show us how to reproduce your issue in detail ?

**Comment by zouxiaoliang** [comment]
## zsh config `vi ~/.zshrc`
```
export PATH="/usr/local/sbin:$PATH"

[ -d "${HOME}/.zgen" ] || git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"

alias zshconfig="vi ~/.zshrc"
alias zgenconfig="vi ~/.my.zgen"

source ~/.my.profile
source ~/.my.zgen
```

## zgen config `vi ~/.my.zgen`
```# my config
# load zgen
source "${HOME}/.zgen/zgen.zsh"

# if the init scipt doesn't exist
if ! zgen saved; then
    echo "Creating a zgen save"

    zgen oh-my-zsh

    # plugins
    zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/sudo
    zgen oh-my-zsh plugins/command-not-found
    zgen oh-my-zsh plugins/python
    zgen oh-my-zsh plugins/pip
    zgen oh-my-zsh plugins/wd
    zgen oh-my-zsh plugins/ruby
    zgen oh-my-zsh plugins/svn
    zgen oh-my-zsh plugins/autojump

    zgen load zsh-users/zsh-autosuggestions
    zgen load zsh-users/zsh-syntax-highlighting

    # bulk load
    zgen loadall <<EOPLUGINS
        zsh-users/zsh-history-substring-search
EOPLUGINS
    # can't indent this EOPLUGINS

    # completions
    zgen load zsh-users/zsh-completions src
    # theme
    zgen load eendroroy/alien-minimal
    # zgen load denysdovhan/spaceship-prompt spaceship

    # save all to init script
    zgen save
fi
```

## step 
* `zgen update`
* new tab in `iTem`
## error
```
Last login: Tue Jul 20 22:46:39 on ttys000
Creating a zgen save
_arguments:comparguments:325: can only be called from completion function
-- zgen: Creating `/Users/zouxiaoliang/.zgen/init.zsh` ...
-- zgen: Initializing completions ...
```

**Comment by rs-ehyde** [comment]
Happening to me as well.

**Comment by oxiedi** [comment]
`_rmlint.sh` is not the only precedent of such a naming scheme. There are at least `_todo.sh` in Zsh and `plugins/_wd.sh` in Oh My Zsh. Zgen probably should not `source` `*.sh` or at least exclude completion functions from the list.

**Comment by syohex** [comment]
Thanks for information. I tried to your configuration with adding log in `-zgen-source` function. Then I got following log. If there are `*.plugin.zsh` or `*.zsh` or `*.sh` under plugin, zgen loads them as plugin configuration files.

```
#### LOAD '/home/syohei/.zgen/robbyrussell/oh-my-zsh-master/oh-my-zsh.sh'
#### LOAD '/home/syohei/.zgen/robbyrussell/oh-my-zsh-master/plugins/git/git.plugin.zsh'
#### LOAD '/home/syohei/.zgen/robbyrussell/oh-my-zsh-master/plugins/sudo/sudo.plugin.zsh'
#### LOAD '/home/syohei/.zgen/robbyrussell/oh-my-zsh-master/plugins/command-not-found/command-not-found.plugin.zsh'
#### LOAD '/home/syohei/.zgen/robbyrussell/oh-my-zsh-master/plugins/python/python.plugin.zsh'
#### LOAD '/home/syohei/.zgen/robbyrussell/oh-my-zsh-master/plugins/pip/pip.plugin.zsh'
#### LOAD '/home/syohei/.zgen/robbyrussell/oh-my-zsh-master/plugins/wd/wd.plugin.zsh'
#### LOAD '/home/syohei/.zgen/robbyrussell/oh-my-zsh-master/plugins/ruby/ruby.plugin.zsh'
#### LOAD '/home/syohei/.zgen/robbyrussell/oh-my-zsh-master/plugins/svn/svn.plugin.zsh'
#### LOAD '/home/syohei/.zgen/robbyrussell/oh-my-zsh-master/plugins/autojump/autojump.plugin.zsh'
#### LOAD '/home/syohei/.zgen/zsh-users/zsh-autosuggestions-master/zsh-autosuggestions.plugin.zsh'
#### LOAD '/home/syohei/.zgen/zsh-users/zsh-syntax-highlighting-master/zsh-syntax-highlighting.plugin.zsh'
#### LOAD '/home/syohei/.zgen/zsh-users/zsh-history-substring-search-master/zsh-history-substring-search.plugin.zsh'
#### LOAD '/home/syohei/.zgen/zsh-users/zsh-completions-master/src/_rmlint.sh'
#### LOAD '/home/syohei/.zgen/eendroroy/alien-minimal-master/alien-minimal.plugin.zsh'
```

**Comment by syohex** [comment]
Files starts with `_` like `_rmfile.sh` is autoloaded file in zsh file name convention. It should not be loaded manually. zgen should avoid loading such files.

BTW zgen looks no longer maintained. It may be difficult to fix this.

**Comment by oxiedi** [comment]
I just noticed that, because of `wd.plugin.zsh`, loading of `oh-my-zsh/plugins/wd` went fine. `zsh-completions` has such a file in the root directory too. I wonder, would Zgen properly load `zsh-completions` without the `src` argument?

**Comment by jandamm** [comment]
Hi, I'm the maintainer of [zgenom](https://github.com/jandamm/zgenom), a fork of zgen with new features and performance improvements.
Which also produced this error.

I've had a look at it and the easiest fix is to remove the `src` argument as @oxiedi suggested.

Here's what happens:
When providing a folder to zgenom it will add the path to fpath which is the wanted behavior in this case.
It also iterates over all files which match *.sh and will source them.
Since zsh-completions has files like _rmlint.sh in this folder they're matched and sourced which is the not wanted behavior - resulting in an error.

**Comment by oxiedi** [comment]
@jandamm So it did work. Thanks for letting me know.

Zgenom's README states:

> useful for repositories that don't have proper plugin support like zsh-users/zsh-completions

Does `zsh-completions` lack something to be identified as a plugin?

**Comment by jandamm** [comment]
This is a relict from the zgen readme which I didn't check 😅

I guess at the time of writing the `zsh-completions.plugin.zsh` didn't exist. Which is the "proper plugin support".

I'll update the Readme later 👍

**Comment by ericbn** [comment]
Replacing

    zgen load zsh-users/zsh-completions src

by

    zgen load zsh-users/zsh-completions

fixed the issue for me.

**Comment by Dadaji18** [comment]
I found this script somwhere and it helped, just copy and paste it into the zsh terminal and the commands will run just fine.
``` zsh
cd ~
mkdir ~/.zsh
swift package completion-tool generate-zsh-script > ~/.zsh/_swift
echo -e "fpath=(~/.zsh \$fpath)\n" >> ~/.zshrc
echo -e "autoload -Uz compinit && compinit" >> ~/.zshrc
```
