### ISSUE TITLE
_rmlint.sh:32: command not found: _arguments

### ISSUE THREAD

**Issue by alezunino** [zsh-users/zsh-completions#811]
Hi,
since #808 I get the following error:
_rmlint.sh:32: command not found: _arguments

I fixed it by removing _rmlint*, which obviously is too drastic...
BTW, I use zgenom

**Comment by oxiedi** [comment]
See #809. TL;DR: update Zgenom and don't point it to the `src` directory.

**Comment by alezunino** [comment]
thanks!
