### ISSUE TITLE
zsh completion doesn't provide completion for targets properly.

### ISSUE THREAD

**Issue by artyom-razinov** [zsh-users/zsh-completions#813]
Where is completion for `make`? I can make completion for make as it is in bash-completions and it is working there.

Problem: if your Makefile has dynamic targets, they don't work.

```
TARGETS := $(echo foo bar)
$(TARGETS):
    echo something
```

Completion for bash and fish works, but zsh outputs something like $(echo foo bar).

Completion for bash (bash-completions) uses list of target provided by `make -qp Makefile make_file_directory`. I bet, zsh doesn't use it and I can't find where completion for make is defined in this repo. It seems like an easy fix, but I only found where completions for cmake, not for make.

**Comment by syohex** [comment]
https://github.com/zsh-users/zsh/blob/master/Completion/Unix/Command/_make

`make` completion is provided by zsh itself, not this repository. 

Mailing list is here
- https://zsh.sourceforge.io/FAQ/zshfaq06.html
- https://www.zsh.org/mla/

**Comment by artyom-razinov** [comment]
I found the answer:
https://github.com/zsh-users/zsh-completions/issues/541

```
zstyle ':completion:*:make:*:targets' call-command true
zstyle ':completion:*:*:make:*' tag-order 'targets' 
```

`make` + TAB:

```
build         clean         generate      open          run_ci_tests  test
```

Works great.
