### ISSUE TITLE
Q: can this package be used as backend for completion engine?

### ISSUE THREAD

**Issue by FelipeLema** [zsh-users/zsh-completions#817]
Hello, there

Can this package be used within an editor (neovim, emacs...) and be called somehow to get completions?

I took [this rather simple script file](https://github.com/tjdevries/coc-zsh/blob/master/bin/capture.zsh) and tried using it [as completion engine](https://codeberg.org/FelipeLema/company-zsh), but, while it looks intriguing at first, through time it becomes unstable and process just hangs there constantly. 

The way the script above works is 

```zsh
zsh capture.zsh some_command_I_want_to_complete_like_git --incomplete-cli-arg < whole_file_being_editing
```

Can this package be used this way?

Thanks

**Comment by syohex** [comment]
I suppose, No. This repository provides only completion files for each commands. There is no framework and no features of completion engines.

**Comment by FelipeLema** [comment]
ok, thanks for the clear answer
