### ISSUE TITLE
Completion  for Yarn 2 run doesn't work

### ISSUE THREAD

**Issue by zyf0330** [zsh-users/zsh-completions#828]
In Yarn 2, `yarn run --json` doesn't work anymore, so completion is bad now.

**Comment by syohex** [comment]
@zyf0330 Do you use latest version ? `yarn run --json` was removed by #827.

**Comment by zyf0330** [comment]
@syohex Yes, actually I use Yarn 3.1.1.

**Comment by syohex** [comment]
Sorry, do you use latest `zsh-completions`, not yarn ?

**Comment by zyf0330** [comment]
@syohex Sorry, I use antigen and just update zsh-completions plugin. Now everything is ok. Thanks alert!
