### ISSUE TITLE
[Yarn] completions print error if in a directory without a package.json

### ISSUE THREAD

**Issue by Machine-Maker** [zsh-users/zsh-completions#829]
Pressing TAB after typing `yarn` while in a directory without a package.json prints out `cat: package.json: No such file or directory` which starts to look like a mess after a while

![image](https://user-images.githubusercontent.com/15055071/146808052-15c6b043-9bc6-45d9-9995-b120a5920e8f.png)

**Comment by syohex** [comment]
Thanks for reporting issue. It's bug. I'll check it later.

**Comment by syohex** [comment]
@Machine-Maker I suppose this issue is fixed by #830. Could you try to use latest version ?

**Comment by Machine-Maker** [comment]
Yep, seems fixed. Thanks so much.
