### ISSUE TITLE
Broken caseinsensitivity / autocompletion when using umlauts.

### ISSUE THREAD

**Issue by Semnodime** [zsh-users/zsh-completions#831]
Suppose there's a subdirectory named `MÜNCHEN` in the current directory, then tab-completion won't recognize this directory, when `cd münchen`<kbd>tab</kbd> is given.

I noticed this behavior when attempting to `cd` the given directory (with tab autocomletion), and while doing the same with `rm -r`.

I assume, **it's a zsh-wide issue due to broken case-insensitive matching umlauts.**

**Comment by syohex** [comment]
Please report your issue to zsh mailing list(https://zsh.sourceforge.io/Arc/mlist.html) about problems of zsh itself. This repository provides only some command completions.
