### ISSUE TITLE
Yarn auto-completions no longer working from package.json scripts

### ISSUE THREAD

**Issue by campbellwmorgan** [zsh-users/zsh-completions#833]
The commit https://github.com/zsh-users/zsh-completions/commit/da037c4ba7eaf06c63eb39e40924ed700329e738#diff-8c0b3a519cc55077ed15e94ee2083a994edbf059cc5376b24ff5281feb6b7b80 seems to have broken my yarn autocompletions from `package.json` scripts.

Previously I could press tab and it would autocomplete from `scripts` in my `package.json`

Currently it only auto completes with `bin` executables.

I'm running Ubuntu 20.04 on the latest commit of `master` on `oh-my-zsh` which incorporated these changes with this PR https://github.com/ohmyzsh/ohmyzsh/pull/10516

Completions previous to that PR work correctly for me.

**Comment by syohex** [comment]
Sorry there is a bug in Perl one liner code. I'll fix this issue at #834

**Comment by syohex** [comment]
I have merged #834. Please check latest version.

**Comment by campbellwmorgan** [comment]
Thank you!
