### ISSUE TITLE
Why does homebrew directs to code file instead of giving brew install ...

### ISSUE THREAD

**Issue by dpthegrey** [zsh-users/zsh-completions#851]
I am trying to find brew install command but the installation readme redirects me to .rb file on clicking homebrew.
Can I just get directions on how to install instead of redirecting the installation readme to the file?

**Comment by abuGit** [comment]
The git  page of homebrrew offers the shell completions : [zshell completion](https://github.com/Homebrew/brew/tree/master/completions/zsh)
