### ISSUE TITLE
git add fails to complete

### ISSUE THREAD

**Issue by Pound-Hash** [zsh-users/zsh-completions#855]
If `compinit` is loaded, then `git add Tab` fails to list any completions. But if `compinit` is _not_ loaded, or if in Bash, then `git add Tab` _does_ list completions.

Other git functions successfully Tab complete.

zsh 5.8.1; Arch; git 2.35.1

**Comment by syohex** [comment]
git completion is provided by zsh itself, not by this repository. If you have any problems, please send email to official mailing list
- https://zsh.sourceforge.io/Arc/mlist.html
