### ISSUE TITLE
how to get 1Password CLI2's completions in here or to just work?

### ISSUE THREAD

**Issue by lrosenman** [zsh-users/zsh-completions#856]
1Password CLI V2 has a completion generator, and I'd love to find a way to get it to work with zsh seamlessly.  

The syntax they suggest doesn't SEEM to work..

https://app-updates.agilebits.com/product_history/CLI2

https://developer.1password.com/docs/cli/upgrade

Any help welcome. 

For the moment I've run `op completion zsh >_op` in my copy of your repo, but... that seems heavy-handed.

**Comment by syohex** [comment]
https://github.com/zsh-users/zsh-completions/blob/master/CONTRIBUTING.md

I'm afraid not that we cannot accept a completion file that is already provided by the original repository
