### ISSUE TITLE
Add Fedora 36 support in OpenSUSE Build Service

### ISSUE THREAD

**Issue by fuzzyyy** [zsh-users/zsh-completions#864]
Hi,
would you please enable the Fedora 36 repository in OBS?

Currently Fedora 35 is the latest Fedora shown when trying to install zsh-completions from the OBS repository linked in readme, but Fedora 36 has been already released.
From a quick google search it seems that simply enabling Fedora 36 repository in the OBS should suffice.

**Comment by nicoulaj** [comment]
done
