### ISSUE TITLE
Flutter 3.0 commands changed

### ISSUE THREAD

**Issue by kinosang** [zsh-users/zsh-completions#866]
Flutter 3.0 has some new commands:

- **custom-devices** List, reset, add and delete custom devices.
- **debug-adapter** Run a Debug Adapter Protocol (DAP) server to communicate with the Flutter tool.
- **downgrade** Downgrade Flutter to the last active version for the current channel.
- **gen-l10n** Generate localizations for the current project.
- **pub** Commands for managing Flutter packages.
- **symbolize** Symbolize a stack trace from an AOT-compiled Flutter app.

Removed commands are:

- **fuchsia_reload**
- **ide-config**
- **inject-plugins**
- **packages**
- **stop**
- **trace**
- **update-packages**
- **version**

Also, new global options:

    --prefixed-errors           Causes lines sent to stderr to be prefixed with "ERROR:".
    --[no-]wrap                 Toggles output word wrapping, regardless of whether or not the output is a terminal.
                                (defaults to on)
    --wrap-column               Sets the output wrap column. If not set, uses the width of the terminal. No wrapping occurs if not
                                writing to a terminal. Use "--no-wrap" to turn off wrapping when connected to a terminal.
    --machine                   When used with the "--version" flag, outputs the information using JSON.
    --[no-]version-check        Allow Flutter to check for updates when this command runs.
                                (defaults to on)
    --local-engine-src-path     Path to your engine src directory, if you are building Flutter locally.
                                Defaults to $FLUTTER_ENGINE if set, otherwise defaults to the path given in your pubspec.yaml
                                dependency_overrides for sky_engine, if any.
    --local-engine              Name of a build output within the engine out directory, if you are building Flutter locally.
                                Use this to select a specific version of the engine if you have built multiple engine targets.
                                This path is relative to "--local-engine-src-path" or "--local-engine-src-out" (q.v.).
    --show-test-device          List the special "flutter-tester" device in device listings. This headless device is used to test
                                Flutter tooling.
    --show-web-server-device    List the special "web-server" device in device listings.

Removed options:

- --bug-report
- --flutter-root

**Comment by kinosang** [comment]
@syohex I'll have a test asap.

**Comment by kinosang** [comment]
@syohex

I didn't test every command nor options, but it seems works well.

**Comment by syohex** [comment]
@kinosang Thanks for reviewing. If you have a issue, please let me know
