### ISSUE TITLE
how to useing zsh-completions ?

### ISSUE THREAD

**Issue by topmask** [zsh-users/zsh-completions#872]
I don't know how this plugin works
Do it need any shortcut keys?

Is it autocomplete?
Why can't I see the effect

**Comment by syohex** [comment]
> Do it need any shortcut keys?

No. You can use completions by `TAB` keys.

> Is it autocomplete?

No.

> Why can't I see the effect

I'm not sure. Could you show us your configurations of `zsh-completions` ?

**Comment by topmask** [comment]
yes tab>>>
