### ISSUE TITLE
Howto: copying completions does not work

### ISSUE THREAD

**Issue by jtyers** [zsh-users/zsh-completions#874]
The [howto copying completions](https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org#copying-completions-from-another-command) section states you can copy a completion from one command to another using:

```
compdef cmd1=cmd2
```

This doesn't appear to work. In my case I have an alias `md`:

```
❯ alias md
md='m env=dev'
```

Given a makefile which works with normal completion via `make`:

```
❯ make [TAB]
[make target]
PHONY
clean
dist
[--snip--]
```

I would expect the same behaviour for `md`, but it doesn't suggest make targets, only files, as if no completion had been defined for it. I'm running `compdef md=make`.

**Comment by syohex** [comment]
I cannot reproduce your issue.

I suppose you don't need to define `compdef` because zsh completion works against aliases.
How about defining alias like `alias md='make env=dev'` ?

**Comment by jtyers** [comment]
Ah, that's true. It'll be causing an issue in my case because I have a
wrapper function for make, so zsh is not seeing it as an invocation to make
any more
