### ISSUE TITLE
Go 1.18 new flags

### ISSUE THREAD

**Issue by Deleplace** [zsh-users/zsh-completions#877]
Hello, I'm trying `zsh-completions` for the first time, to use it with `go` subcommands and flags.

I can see that some recent options are missing, e.g.
`go test -fu<TAB>` ->  no completion, I would expect `go test -fuzz`

Shall I manually list the missing flags and open a PR to add them to [src/_golang](https://github.com/zsh-users/zsh-completions/blob/dd45d21d06118a70ac5b42a7968706108f6494dc/src/_golang#L645) ?

Thanks!

**Comment by syohex** [comment]
Thanks for the suggestion. I have merged #878
