### ISSUE TITLE
CMAKE generators list

### ISSUE THREAD

**Issue by hinell** [zsh-users/zsh-completions#885]
From [cmake-generators.7](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#introduction) it follows, that:
> ... _command-line tool `--help` output lists available **generators on the current platform**_

but currently we only have a hard-wired list of available generators:
https://github.com/zsh-users/zsh-completions/blob/b131623ee4c46aa9a781213a3ba0e4cfd020b810/src/_cmake#L470-L486

I propose to make a list platform-dependent. Any thoughts?

**Comment by syohex** [comment]
https://github.com/zsh-users/zsh-completions/compare/cmake-generator

How about the above change ?

**Comment by hinell** [comment]
Yeah, definitely.
