### ISSUE TITLE
Is there a way to pipe zsh completions to another command?

### ISSUE THREAD

**Issue by jmfayard** [zsh-users/zsh-completions#890]
Bonjour, and apologies if I am not asking this question in the right place

Question: is there a command I can execute to capture what `zsh` would propose as completion possibilities?

Context: I have an idea for a side-project that would work like this:

```bash
$ explain ls -a -l --color --whatever
Command:
ls    list directory contents

Options:
-a             -- Show hidden and 'dot' files
-1             -- Display one entry per line

Invalid options:
--color       -- did you mean --colour?
```

For this to work, it would be great if I could capture the standard output of zsh completion like this:

```bash
$ ls -<TAB>
--accessed                 -u             -- Use the accessed timestamp field
--across                   -x             -- Sort the grid across, rather than downwards
--all                      -a             -- Show hidden and 'dot' files
--binary                   -b             -- List file sizes with binary prefixes
...
$ ls -<TAB> > /tmp/ls-completions.txt
```

Do you think that's possible?

**Comment by syohex** [comment]
I think that there is no way. I suppose it is better to ask to zsh mailing list rather than here.

https://zsh.sourceforge.io/Arc/mlist.html
