### ISSUE TITLE
What does 'additional' refer to?

### ISSUE THREAD

**Issue by memark** [zsh-users/zsh-completions#899]
From the README:

>Additional completion definitions

and

>new completion scripts that are not available in Zsh yet. 

I'm quite new with zsh completions, but what does 'additional' refer to? Are there a number of bundled completions already in zsh that I have missed? How would I use them?

**Comment by syohex** [comment]
It means completion definitions that this repository provides. zsh provides a lot of completion definitions itself. You can find them https://github.com/zsh-users/zsh/tree/master/Completion
