### ISSUE TITLE
Completions are case sensitive

### ISSUE THREAD

**Issue by cybersaksham** [zsh-users/zsh-completions#900]
ZSH completions are case sensitive. Most of the time we need them to be case insensitive like fish

**Comment by syohex** [comment]
You can modify the behavior by modifying `matcher-list` as below.

- https://superuser.com/questions/1092033/how-can-i-make-zsh-tab-completion-fix-capitalization-errors-for-directories-and
- https://gist.github.com/nhibberd/9d78576aab943cdb0f6c
