### ISSUE TITLE
`yarn run` package script completions fail for Yarn v4

### ISSUE THREAD

**Issue by bitjson** [zsh-users/zsh-completions#981]
When upgrading a project to use [Yarn v3's zero-install strategy](https://yarnpkg.com/features/zero-installs#how-do-you-reach-this-zero-install-state-youre-advocating-for), completions stop working for package scripts.

E.g. using [`create-react-app`](https://create-react-app.dev/):

```zsh
❯ yarn create react-app yarn-v3-test-project
[...]

❯ cd yarn-v3-test
❯ yarn --version
1.22.19

❯  yarn run [tab]
build                     -- react-scripts build
eject                     -- react-scripts eject
start                     -- react-scripts start
test                      -- react-scripts test

❯ yarn set version stable
➤ YN0000: Retrieving https://repo.yarnpkg.com/3.3.1/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-3.3.1.cjs
➤ YN0000: Done in 0s 371ms

❯ yarn --version
3.3.1

❯ yarn run [tab]
# (error sound plays)
```

**Comment by syohex** [comment]
@bitjson Thanks for reporting issue. However I can't reproduce. Do you have `perl` command in your machine ?  [yarn completion](https://github.com/zsh-users/zsh-completions/blob/master/src/_yarn) uses perl.

**Comment by bitjson** [comment]
Thanks for reviewing!

Yes:

```
❯ perl --version

This is perl 5, version 30, subversion 3 (v5.30.3) built for darwin-thread-multi-2level
```

Note, completions are working properly for me in repos where I haven't upgraded to Yarn v3, it only fails after I run `yarn set version stable` in a particular repo.

Are you able to use completions with Yarn v3? (Any recommendations for how I can debug what's happening?)

**Comment by syohex** [comment]
Thanks I see. I'll try to reproduce this.
