### ISSUE TITLE
git-wtf completion only works after switching branches

### ISSUE THREAD

**Issue by MeisterP** [zsh-users/zsh-completions#99]
`git-wtf <TAB> git-wtf _arguments:450: command not found: __git_branch_names 
_arguments:450: command not found: __git_branch_names
_arguments:450: command not found: __git_branch_names`

After switching branches, the completion works correct.

The same issue is mentioned here:
https://github.com/zsh-users/zsh-completions/commit/07ce97ed85515cbb3fbd3f49c3f22b405df663fc#commitcomment-847879

**Comment by syohex** [comment]
Please check latest version

**Comment by pjg** [comment]
Latest version fixes this issue. Thanks!
