### ISSUE TITLE
OBS repository for Fedora 37

### ISSUE THREAD

**Issue by madjxatw** [zsh-users/zsh-completions#991]
There is no OBS repo for Fedora 37 so far, should I keep using the F36 repo or rawhide?

**Comment by syohex** [comment]
I'm sorry that I'm not sure because I don't familiar with fedora packaging. Could you try both of them or ask someone else who is familiar with fedora at reddit or stackoverflow etc ?

**Comment by madjxatw** [comment]
OK, I am gonna ask some Fedora guys elsewhere, thanks for your response anyway.
